database:
  # Configuration for SQLite
  SQLite:
    # name of the file with the saved data
    file: "notlibtest"
    # name of the table with the saved data
    table: 'NotCredits'

  MySQL:
    # host of the MySQL server
    host: '127.0.0.1'
    # port of the MySQL server
    port: 3306
    # username of the MySQL server
    username: 'root'
    # password of the MySQL server
    password: ''
    # database of the MySQL server
    database: 'notlib'

  NotDevTestMySQL:
    MySQL:
    # host of the MySQL server
    host: '127.0.0.1'
    # port of the MySQL server
    port: 3306
    # username of the MySQL server
    username: 'root'
    # password of the MySQL server
    password: ''
    # database of the MySQL server
    database: 'notlib'