database:
  use: "SQLite"

  # Configuration for SQLite
  SQLite:
    # name of the file with the saved data
    file: "notlibtest"
    # name of the table with the saved data
    table: 'NotCredits'

  MySQL:
    # host of the MySQL server
    host: ''
    # port of the MySQL server
    port: 3306
    # username of the MySQL server
    username: ''
    # password of the MySQL server
    password: ''
    # database of the MySQL server
    database: ''
    # table of the MySQL server
    table: 'NotCredits'