name: NotLib
version: '1.0-DEV'
main: dev.notmarra.notlib.NotLib
api-version: '1.21'
author: "NotMarra"
loader: dev.notmarra.notlib.utils.PaperLibLoader

dependencies:
  bootstrap: {}
  server: {}

paper-skip-libraries: false

libraries:
  - org.xerial:sqlite-jdbc:3.51.2.0
  - org.mariadb.jdbc:mariadb-java-client:3.5.7