name: NotLib
version: '1.0-DEV'
main: dev.notmarra.notlib.NotLib
api-version: '1.21'

dependencies:
  bootstrap: {}
  server: {}

paper-skip-libraries: false

libraries:
  - org.xerial:sqlite-jdbc:3.51.2.0