package com.notmarra.notlib.font;

import javax.annotation.Nullable;

import org.bukkit.Material;

public class NotFontItem {
    public static final Character ACACIA_BOAT = '\ue36b';
    public static final Character ACACIA_CHEST_BOAT = '\ue36c';
    public static final Character ACACIA_DOOR = '\ue36d';
    public static final Character ACACIA_HANGING_SIGN = '\ue36e';
    public static final Character ACACIA_SIGN = '\ue36f';
    public static final Character AMETHYST_SHARD = '\ue370';
    public static final Character APPLE = '\ue371';
    public static final Character ARMOR_STAND = '\ue372';
    public static final Character ARROW = '\ue373';
    public static final Character AXOLOTL_BUCKET = '\ue374';
    public static final Character BAKED_POTATO = '\ue375';
    public static final Character BAMBOO = '\ue376';
    public static final Character BAMBOO_CHEST_RAFT = '\ue377';
    public static final Character BAMBOO_DOOR = '\ue378';
    public static final Character BAMBOO_HANGING_SIGN = '\ue379';
    public static final Character BAMBOO_RAFT = '\ue37a';
    public static final Character BAMBOO_SIGN = '\ue37b';
    public static final Character BARRIER = '\ue37c';
    public static final Character BEEF = '\ue37d';
    public static final Character BEETROOT = '\ue37e';
    public static final Character BEETROOT_SEEDS = '\ue37f';
    public static final Character BEETROOT_SOUP = '\ue380';
    public static final Character BELL = '\ue381';
    public static final Character BIRCH_BOAT = '\ue382';
    public static final Character BIRCH_CHEST_BOAT = '\ue383';
    public static final Character BIRCH_DOOR = '\ue384';
    public static final Character BIRCH_HANGING_SIGN = '\ue385';
    public static final Character BIRCH_SIGN = '\ue386';
    public static final Character BLACK_CANDLE = '\ue387';
    public static final Character BLACK_DYE = '\ue388';
    public static final Character BLAZE_POWDER = '\ue389';
    public static final Character BLAZE_ROD = '\ue38a';
    public static final Character BLUE_CANDLE = '\ue38b';
    public static final Character BLUE_DYE = '\ue38c';
    public static final Character BONE = '\ue38d';
    public static final Character BONE_MEAL = '\ue38e';
    public static final Character BOOK = '\ue38f';
    public static final Character BOW = '\ue390';
    public static final Character BOWL = '\ue391';
    public static final Character BOW_PULLING_0 = '\ue392';
    public static final Character BOW_PULLING_1 = '\ue393';
    public static final Character BOW_PULLING_2 = '\ue394';
    public static final Character BREAD = '\ue395';
    public static final Character BREWING_STAND = '\ue396';
    public static final Character BRICK = '\ue397';
    public static final Character BROKEN_ELYTRA = '\ue398';
    public static final Character BROWN_CANDLE = '\ue399';
    public static final Character BROWN_DYE = '\ue39a';
    public static final Character BUCKET = '\ue39b';
    public static final Character BUNDLE = '\ue39c';
    public static final Character BUNDLE_FILLED = '\ue39d';
    public static final Character CAKE = '\ue39e';
    public static final Character CAMPFIRE = '\ue39f';
    public static final Character CANDLE = '\ue3a0';
    public static final Character CARROT = '\ue3a1';
    public static final Character CARROT_ON_A_STICK = '\ue3a2';
    public static final Character CAULDRON = '\ue3a3';
    public static final Character CHAIN = '\ue3a4';
    public static final Character CHAINMAIL_BOOTS = '\ue3a5';
    public static final Character CHAINMAIL_CHESTPLATE = '\ue3a6';
    public static final Character CHAINMAIL_HELMET = '\ue3a7';
    public static final Character CHAINMAIL_LEGGINGS = '\ue3a8';
    public static final Character CHARCOAL = '\ue3a9';
    public static final Character CHEST_MINECART = '\ue3aa';
    public static final Character CHICKEN = '\ue3ab';
    public static final Character CHORUS_FRUIT = '\ue3ac';
    public static final Character CLAY_BALL = '\ue3ad';
    public static final Character CLOCK_00 = '\ue3ae';
    public static final Character CLOCK_01 = '\ue3af';
    public static final Character CLOCK_02 = '\ue3b0';
    public static final Character CLOCK_03 = '\ue3b1';
    public static final Character CLOCK_04 = '\ue3b2';
    public static final Character CLOCK_05 = '\ue3b3';
    public static final Character CLOCK_06 = '\ue3b4';
    public static final Character CLOCK_07 = '\ue3b5';
    public static final Character CLOCK_08 = '\ue3b6';
    public static final Character CLOCK_09 = '\ue3b7';
    public static final Character CLOCK_10 = '\ue3b8';
    public static final Character CLOCK_11 = '\ue3b9';
    public static final Character CLOCK_12 = '\ue3ba';
    public static final Character CLOCK_13 = '\ue3bb';
    public static final Character CLOCK_14 = '\ue3bc';
    public static final Character CLOCK_15 = '\ue3bd';
    public static final Character CLOCK_16 = '\ue3be';
    public static final Character CLOCK_17 = '\ue3bf';
    public static final Character CLOCK_18 = '\ue3c0';
    public static final Character CLOCK_19 = '\ue3c1';
    public static final Character CLOCK_20 = '\ue3c2';
    public static final Character CLOCK_21 = '\ue3c3';
    public static final Character CLOCK_22 = '\ue3c4';
    public static final Character CLOCK_23 = '\ue3c5';
    public static final Character CLOCK_24 = '\ue3c6';
    public static final Character CLOCK_25 = '\ue3c7';
    public static final Character CLOCK_26 = '\ue3c8';
    public static final Character CLOCK_27 = '\ue3c9';
    public static final Character CLOCK_28 = '\ue3ca';
    public static final Character CLOCK_29 = '\ue3cb';
    public static final Character CLOCK_30 = '\ue3cc';
    public static final Character CLOCK_31 = '\ue3cd';
    public static final Character CLOCK_32 = '\ue3ce';
    public static final Character CLOCK_33 = '\ue3cf';
    public static final Character CLOCK_34 = '\ue3d0';
    public static final Character CLOCK_35 = '\ue3d1';
    public static final Character CLOCK_36 = '\ue3d2';
    public static final Character CLOCK_37 = '\ue3d3';
    public static final Character CLOCK_38 = '\ue3d4';
    public static final Character CLOCK_39 = '\ue3d5';
    public static final Character CLOCK_40 = '\ue3d6';
    public static final Character CLOCK_41 = '\ue3d7';
    public static final Character CLOCK_42 = '\ue3d8';
    public static final Character CLOCK_43 = '\ue3d9';
    public static final Character CLOCK_44 = '\ue3da';
    public static final Character CLOCK_45 = '\ue3db';
    public static final Character CLOCK_46 = '\ue3dc';
    public static final Character CLOCK_47 = '\ue3dd';
    public static final Character CLOCK_48 = '\ue3de';
    public static final Character CLOCK_49 = '\ue3df';
    public static final Character CLOCK_50 = '\ue3e0';
    public static final Character CLOCK_51 = '\ue3e1';
    public static final Character CLOCK_52 = '\ue3e2';
    public static final Character CLOCK_53 = '\ue3e3';
    public static final Character CLOCK_54 = '\ue3e4';
    public static final Character CLOCK_55 = '\ue3e5';
    public static final Character CLOCK_56 = '\ue3e6';
    public static final Character CLOCK_57 = '\ue3e7';
    public static final Character CLOCK_58 = '\ue3e8';
    public static final Character CLOCK_59 = '\ue3e9';
    public static final Character CLOCK_60 = '\ue3ea';
    public static final Character CLOCK_61 = '\ue3eb';
    public static final Character CLOCK_62 = '\ue3ec';
    public static final Character CLOCK_63 = '\ue3ed';
    public static final Character COAL = '\ue3ee';
    public static final Character COCOA_BEANS = '\ue3ef';
    public static final Character COD = '\ue3f0';
    public static final Character COD_BUCKET = '\ue3f1';
    public static final Character COMMAND_BLOCK_MINECART = '\ue3f2';
    public static final Character COMPARATOR = '\ue3f3';
    public static final Character COMPASS_00 = '\ue3f4';
    public static final Character COMPASS_01 = '\ue3f5';
    public static final Character COMPASS_02 = '\ue3f6';
    public static final Character COMPASS_03 = '\ue3f7';
    public static final Character COMPASS_04 = '\ue3f8';
    public static final Character COMPASS_05 = '\ue3f9';
    public static final Character COMPASS_06 = '\ue3fa';
    public static final Character COMPASS_07 = '\ue3fb';
    public static final Character COMPASS_08 = '\ue3fc';
    public static final Character COMPASS_09 = '\ue3fd';
    public static final Character COMPASS_10 = '\ue3fe';
    public static final Character COMPASS_11 = '\ue3ff';
    public static final Character COMPASS_12 = '\ue400';
    public static final Character COMPASS_13 = '\ue401';
    public static final Character COMPASS_14 = '\ue402';
    public static final Character COMPASS_15 = '\ue403';
    public static final Character COMPASS_16 = '\ue404';
    public static final Character COMPASS_17 = '\ue405';
    public static final Character COMPASS_18 = '\ue406';
    public static final Character COMPASS_19 = '\ue407';
    public static final Character COMPASS_20 = '\ue408';
    public static final Character COMPASS_21 = '\ue409';
    public static final Character COMPASS_22 = '\ue40a';
    public static final Character COMPASS_23 = '\ue40b';
    public static final Character COMPASS_24 = '\ue40c';
    public static final Character COMPASS_25 = '\ue40d';
    public static final Character COMPASS_26 = '\ue40e';
    public static final Character COMPASS_27 = '\ue40f';
    public static final Character COMPASS_28 = '\ue410';
    public static final Character COMPASS_29 = '\ue411';
    public static final Character COMPASS_30 = '\ue412';
    public static final Character COMPASS_31 = '\ue413';
    public static final Character COOKED_BEEF = '\ue414';
    public static final Character COOKED_CHICKEN = '\ue415';
    public static final Character COOKED_COD = '\ue416';
    public static final Character COOKED_MUTTON = '\ue417';
    public static final Character COOKED_PORKCHOP = '\ue418';
    public static final Character COOKED_RABBIT = '\ue419';
    public static final Character COOKED_SALMON = '\ue41a';
    public static final Character COOKIE = '\ue41b';
    public static final Character COPPER_INGOT = '\ue41c';
    public static final Character CREEPER_BANNER_PATTERN = '\ue41d';
    public static final Character CRIMSON_DOOR = '\ue41e';
    public static final Character CRIMSON_HANGING_SIGN = '\ue41f';
    public static final Character CRIMSON_SIGN = '\ue420';
    public static final Character CROSSBOW_ARROW = '\ue421';
    public static final Character CROSSBOW_FIREWORK = '\ue422';
    public static final Character CROSSBOW_PULLING_0 = '\ue423';
    public static final Character CROSSBOW_PULLING_1 = '\ue424';
    public static final Character CROSSBOW_PULLING_2 = '\ue425';
    public static final Character CROSSBOW_STANDBY = '\ue426';
    public static final Character CYAN_CANDLE = '\ue427';
    public static final Character CYAN_DYE = '\ue428';
    public static final Character DARK_OAK_BOAT = '\ue429';
    public static final Character DARK_OAK_CHEST_BOAT = '\ue42a';
    public static final Character DARK_OAK_DOOR = '\ue42b';
    public static final Character DARK_OAK_HANGING_SIGN = '\ue42c';
    public static final Character DARK_OAK_SIGN = '\ue42d';
    public static final Character DIAMOND = '\ue42e';
    public static final Character DIAMOND_AXE = '\ue42f';
    public static final Character DIAMOND_BOOTS = '\ue430';
    public static final Character DIAMOND_CHESTPLATE = '\ue431';
    public static final Character DIAMOND_HELMET = '\ue432';
    public static final Character DIAMOND_HOE = '\ue433';
    public static final Character DIAMOND_HORSE_ARMOR = '\ue434';
    public static final Character DIAMOND_LEGGINGS = '\ue435';
    public static final Character DIAMOND_PICKAXE = '\ue436';
    public static final Character DIAMOND_SHOVEL = '\ue437';
    public static final Character DIAMOND_SWORD = '\ue438';
    public static final Character DISC_FRAGMENT_5 = '\ue439';
    public static final Character DRAGON_BREATH = '\ue43a';
    public static final Character DRIED_KELP = '\ue43b';
    public static final Character ECHO_SHARD = '\ue43c';
    public static final Character EGG = '\ue43d';
    public static final Character ELYTRA = '\ue43e';
    public static final Character EMERALD = '\ue43f';
    public static final Character EMPTY_ARMOR_SLOT_BOOTS = '\ue440';
    public static final Character EMPTY_ARMOR_SLOT_CHESTPLATE = '\ue441';
    public static final Character EMPTY_ARMOR_SLOT_HELMET = '\ue442';
    public static final Character EMPTY_ARMOR_SLOT_LEGGINGS = '\ue443';
    public static final Character EMPTY_ARMOR_SLOT_SHIELD = '\ue444';
    public static final Character ENCHANTED_BOOK = '\ue445';
    public static final Character ENDER_EYE = '\ue446';
    public static final Character ENDER_PEARL = '\ue447';
    public static final Character END_CRYSTAL = '\ue448';
    public static final Character EXPERIENCE_BOTTLE = '\ue449';
    public static final Character FEATHER = '\ue44a';
    public static final Character FERMENTED_SPIDER_EYE = '\ue44b';
    public static final Character FILLED_MAP = '\ue44c';
    public static final Character FILLED_MAP_MARKINGS = '\ue44d';
    public static final Character FIREWORK_ROCKET = '\ue44e';
    public static final Character FIREWORK_STAR = '\ue44f';
    public static final Character FIREWORK_STAR_OVERLAY = '\ue450';
    public static final Character FIRE_CHARGE = '\ue451';
    public static final Character FISHING_ROD = '\ue452';
    public static final Character FISHING_ROD_CAST = '\ue453';
    public static final Character FLINT = '\ue454';
    public static final Character FLINT_AND_STEEL = '\ue455';
    public static final Character FLOWER_BANNER_PATTERN = '\ue456';
    public static final Character FLOWER_POT = '\ue457';
    public static final Character FURNACE_MINECART = '\ue458';
    public static final Character GHAST_TEAR = '\ue459';
    public static final Character GLASS_BOTTLE = '\ue45a';
    public static final Character GLISTERING_MELON_SLICE = '\ue45b';
    public static final Character GLOBE_BANNER_PATTERN = '\ue45c';
    public static final Character GLOWSTONE_DUST = '\ue45d';
    public static final Character GLOW_BERRIES = '\ue45e';
    public static final Character GLOW_INK_SAC = '\ue45f';
    public static final Character GLOW_ITEM_FRAME = '\ue460';
    public static final Character GOAT_HORN = '\ue461';
    public static final Character GOLDEN_APPLE = '\ue462';
    public static final Character GOLDEN_AXE = '\ue463';
    public static final Character GOLDEN_BOOTS = '\ue464';
    public static final Character GOLDEN_CARROT = '\ue465';
    public static final Character GOLDEN_CHESTPLATE = '\ue466';
    public static final Character GOLDEN_HELMET = '\ue467';
    public static final Character GOLDEN_HOE = '\ue468';
    public static final Character GOLDEN_HORSE_ARMOR = '\ue469';
    public static final Character GOLDEN_LEGGINGS = '\ue46a';
    public static final Character GOLDEN_PICKAXE = '\ue46b';
    public static final Character GOLDEN_SHOVEL = '\ue46c';
    public static final Character GOLDEN_SWORD = '\ue46d';
    public static final Character GOLD_INGOT = '\ue46e';
    public static final Character GOLD_NUGGET = '\ue46f';
    public static final Character GRAY_CANDLE = '\ue470';
    public static final Character GRAY_DYE = '\ue471';
    public static final Character GREEN_CANDLE = '\ue472';
    public static final Character GREEN_DYE = '\ue473';
    public static final Character GUNPOWDER = '\ue474';
    public static final Character HEART_OF_THE_SEA = '\ue475';
    public static final Character HONEYCOMB = '\ue476';
    public static final Character HONEY_BOTTLE = '\ue477';
    public static final Character HOPPER = '\ue478';
    public static final Character HOPPER_MINECART = '\ue479';
    public static final Character INK_SAC = '\ue47a';
    public static final Character IRON_AXE = '\ue47b';
    public static final Character IRON_BOOTS = '\ue47c';
    public static final Character IRON_CHESTPLATE = '\ue47d';
    public static final Character IRON_DOOR = '\ue47e';
    public static final Character IRON_HELMET = '\ue47f';
    public static final Character IRON_HOE = '\ue480';
    public static final Character IRON_HORSE_ARMOR = '\ue481';
    public static final Character IRON_INGOT = '\ue482';
    public static final Character IRON_LEGGINGS = '\ue483';
    public static final Character IRON_NUGGET = '\ue484';
    public static final Character IRON_PICKAXE = '\ue485';
    public static final Character IRON_SHOVEL = '\ue486';
    public static final Character IRON_SWORD = '\ue487';
    public static final Character ITEM_FRAME = '\ue488';
    public static final Character JUNGLE_BOAT = '\ue489';
    public static final Character JUNGLE_CHEST_BOAT = '\ue48a';
    public static final Character JUNGLE_DOOR = '\ue48b';
    public static final Character JUNGLE_HANGING_SIGN = '\ue48c';
    public static final Character JUNGLE_SIGN = '\ue48d';
    public static final Character KELP = '\ue48e';
    public static final Character KNOWLEDGE_BOOK = '\ue48f';
    public static final Character LANTERN = '\ue490';
    public static final Character LAPIS_LAZULI = '\ue491';
    public static final Character LAVA_BUCKET = '\ue492';
    public static final Character LEAD = '\ue493';
    public static final Character LEATHER = '\ue494';
    public static final Character LEATHER_BOOTS = '\ue495';
    public static final Character LEATHER_BOOTS_OVERLAY = '\ue496';
    public static final Character LEATHER_CHESTPLATE = '\ue497';
    public static final Character LEATHER_CHESTPLATE_OVERLAY = '\ue498';
    public static final Character LEATHER_HELMET = '\ue499';
    public static final Character LEATHER_HELMET_OVERLAY = '\ue49a';
    public static final Character LEATHER_HORSE_ARMOR = '\ue49b';
    public static final Character LEATHER_LEGGINGS = '\ue49c';
    public static final Character LEATHER_LEGGINGS_OVERLAY = '\ue49d';
    public static final Character LIGHT = '\ue49e';
    public static final Character LIGHT_00 = '\ue49f';
    public static final Character LIGHT_01 = '\ue4a0';
    public static final Character LIGHT_02 = '\ue4a1';
    public static final Character LIGHT_03 = '\ue4a2';
    public static final Character LIGHT_04 = '\ue4a3';
    public static final Character LIGHT_05 = '\ue4a4';
    public static final Character LIGHT_06 = '\ue4a5';
    public static final Character LIGHT_07 = '\ue4a6';
    public static final Character LIGHT_08 = '\ue4a7';
    public static final Character LIGHT_09 = '\ue4a8';
    public static final Character LIGHT_10 = '\ue4a9';
    public static final Character LIGHT_11 = '\ue4aa';
    public static final Character LIGHT_12 = '\ue4ab';
    public static final Character LIGHT_13 = '\ue4ac';
    public static final Character LIGHT_14 = '\ue4ad';
    public static final Character LIGHT_15 = '\ue4ae';
    public static final Character LIGHT_BLUE_CANDLE = '\ue4af';
    public static final Character LIGHT_BLUE_DYE = '\ue4b0';
    public static final Character LIGHT_GRAY_CANDLE = '\ue4b1';
    public static final Character LIGHT_GRAY_DYE = '\ue4b2';
    public static final Character LIME_CANDLE = '\ue4b3';
    public static final Character LIME_DYE = '\ue4b4';
    public static final Character LINGERING_POTION = '\ue4b5';
    public static final Character MAGENTA_CANDLE = '\ue4b6';
    public static final Character MAGENTA_DYE = '\ue4b7';
    public static final Character MAGMA_CREAM = '\ue4b8';
    public static final Character MANGROVE_BOAT = '\ue4b9';
    public static final Character MANGROVE_CHEST_BOAT = '\ue4ba';
    public static final Character MANGROVE_DOOR = '\ue4bb';
    public static final Character MANGROVE_HANGING_SIGN = '\ue4bc';
    public static final Character MANGROVE_PROPAGULE = '\ue4bd';
    public static final Character MANGROVE_SIGN = '\ue4be';
    public static final Character MAP = '\ue4bf';
    public static final Character MELON_SEEDS = '\ue4c0';
    public static final Character MELON_SLICE = '\ue4c1';
    public static final Character MILK_BUCKET = '\ue4c2';
    public static final Character MINECART = '\ue4c3';
    public static final Character MOJANG_BANNER_PATTERN = '\ue4c4';
    public static final Character MUSHROOM_STEW = '\ue4c5';
    public static final Character MUSIC_DISC_11 = '\ue4c6';
    public static final Character MUSIC_DISC_13 = '\ue4c7';
    public static final Character MUSIC_DISC_5 = '\ue4c8';
    public static final Character MUSIC_DISC_BLOCKS = '\ue4c9';
    public static final Character MUSIC_DISC_CAT = '\ue4ca';
    public static final Character MUSIC_DISC_CHIRP = '\ue4cb';
    public static final Character MUSIC_DISC_FAR = '\ue4cc';
    public static final Character MUSIC_DISC_MALL = '\ue4cd';
    public static final Character MUSIC_DISC_MELLOHI = '\ue4ce';
    public static final Character MUSIC_DISC_OTHERSIDE = '\ue4cf';
    public static final Character MUSIC_DISC_PIGSTEP = '\ue4d0';
    public static final Character MUSIC_DISC_STAL = '\ue4d1';
    public static final Character MUSIC_DISC_STRAD = '\ue4d2';
    public static final Character MUSIC_DISC_WAIT = '\ue4d3';
    public static final Character MUSIC_DISC_WARD = '\ue4d4';
    public static final Character MUTTON = '\ue4d5';
    public static final Character NAME_TAG = '\ue4d6';
    public static final Character NAUTILUS_SHELL = '\ue4d7';
    public static final Character NETHERITE_AXE = '\ue4d8';
    public static final Character NETHERITE_BOOTS = '\ue4d9';
    public static final Character NETHERITE_CHESTPLATE = '\ue4da';
    public static final Character NETHERITE_HELMET = '\ue4db';
    public static final Character NETHERITE_HOE = '\ue4dc';
    public static final Character NETHERITE_INGOT = '\ue4dd';
    public static final Character NETHERITE_LEGGINGS = '\ue4de';
    public static final Character NETHERITE_PICKAXE = '\ue4df';
    public static final Character NETHERITE_SCRAP = '\ue4e0';
    public static final Character NETHERITE_SHOVEL = '\ue4e1';
    public static final Character NETHERITE_SWORD = '\ue4e2';
    public static final Character NETHER_BRICK = '\ue4e3';
    public static final Character NETHER_SPROUTS = '\ue4e4';
    public static final Character NETHER_STAR = '\ue4e5';
    public static final Character NETHER_WART = '\ue4e6';
    public static final Character OAK_BOAT = '\ue4e7';
    public static final Character OAK_CHEST_BOAT = '\ue4e8';
    public static final Character OAK_DOOR = '\ue4e9';
    public static final Character OAK_HANGING_SIGN = '\ue4ea';
    public static final Character OAK_SIGN = '\ue4eb';
    public static final Character ORANGE_CANDLE = '\ue4ec';
    public static final Character ORANGE_DYE = '\ue4ed';
    public static final Character PAINTING = '\ue4ee';
    public static final Character PAPER = '\ue4ef';
    public static final Character PHANTOM_MEMBRANE = '\ue4f0';
    public static final Character PIGLIN_BANNER_PATTERN = '\ue4f1';
    public static final Character PINK_CANDLE = '\ue4f2';
    public static final Character PINK_DYE = '\ue4f3';
    public static final Character POINTED_DRIPSTONE = '\ue4f4';
    public static final Character POISONOUS_POTATO = '\ue4f5';
    public static final Character POPPED_CHORUS_FRUIT = '\ue4f6';
    public static final Character PORKCHOP = '\ue4f7';
    public static final Character POTATO = '\ue4f8';
    public static final Character POTION = '\ue4f9';
    public static final Character POTION_OVERLAY = '\ue4fa';
    public static final Character POWDER_SNOW_BUCKET = '\ue4fb';
    public static final Character PRISMARINE_CRYSTALS = '\ue4fc';
    public static final Character PRISMARINE_SHARD = '\ue4fd';
    public static final Character PUFFERFISH = '\ue4fe';
    public static final Character PUFFERFISH_BUCKET = '\ue4ff';
    public static final Character PUMPKIN_PIE = '\ue500';
    public static final Character PUMPKIN_SEEDS = '\ue501';
    public static final Character PURPLE_CANDLE = '\ue502';
    public static final Character PURPLE_DYE = '\ue503';
    public static final Character QUARTZ = '\ue504';
    public static final Character RABBIT = '\ue505';
    public static final Character RABBIT_FOOT = '\ue506';
    public static final Character RABBIT_HIDE = '\ue507';
    public static final Character RABBIT_STEW = '\ue508';
    public static final Character RAW_COPPER = '\ue509';
    public static final Character RAW_GOLD = '\ue50a';
    public static final Character RAW_IRON = '\ue50b';
    public static final Character RECOVERY_COMPASS_00 = '\ue50c';
    public static final Character RECOVERY_COMPASS_01 = '\ue50d';
    public static final Character RECOVERY_COMPASS_02 = '\ue50e';
    public static final Character RECOVERY_COMPASS_03 = '\ue50f';
    public static final Character RECOVERY_COMPASS_04 = '\ue510';
    public static final Character RECOVERY_COMPASS_05 = '\ue511';
    public static final Character RECOVERY_COMPASS_06 = '\ue512';
    public static final Character RECOVERY_COMPASS_07 = '\ue513';
    public static final Character RECOVERY_COMPASS_08 = '\ue514';
    public static final Character RECOVERY_COMPASS_09 = '\ue515';
    public static final Character RECOVERY_COMPASS_10 = '\ue516';
    public static final Character RECOVERY_COMPASS_11 = '\ue517';
    public static final Character RECOVERY_COMPASS_12 = '\ue518';
    public static final Character RECOVERY_COMPASS_13 = '\ue519';
    public static final Character RECOVERY_COMPASS_14 = '\ue51a';
    public static final Character RECOVERY_COMPASS_15 = '\ue51b';
    public static final Character RECOVERY_COMPASS_16 = '\ue51c';
    public static final Character RECOVERY_COMPASS_17 = '\ue51d';
    public static final Character RECOVERY_COMPASS_18 = '\ue51e';
    public static final Character RECOVERY_COMPASS_19 = '\ue51f';
    public static final Character RECOVERY_COMPASS_20 = '\ue520';
    public static final Character RECOVERY_COMPASS_21 = '\ue521';
    public static final Character RECOVERY_COMPASS_22 = '\ue522';
    public static final Character RECOVERY_COMPASS_23 = '\ue523';
    public static final Character RECOVERY_COMPASS_24 = '\ue524';
    public static final Character RECOVERY_COMPASS_25 = '\ue525';
    public static final Character RECOVERY_COMPASS_26 = '\ue526';
    public static final Character RECOVERY_COMPASS_27 = '\ue527';
    public static final Character RECOVERY_COMPASS_28 = '\ue528';
    public static final Character RECOVERY_COMPASS_29 = '\ue529';
    public static final Character RECOVERY_COMPASS_30 = '\ue52a';
    public static final Character RECOVERY_COMPASS_31 = '\ue52b';
    public static final Character REDSTONE = '\ue52c';
    public static final Character RED_CANDLE = '\ue52d';
    public static final Character RED_DYE = '\ue52e';
    public static final Character REPEATER = '\ue52f';
    public static final Character ROTTEN_FLESH = '\ue530';
    public static final Character SADDLE = '\ue531';
    public static final Character SALMON = '\ue532';
    public static final Character SALMON_BUCKET = '\ue533';
    public static final Character SCUTE = '\ue534';
    public static final Character SEAGRASS = '\ue535';
    public static final Character SEA_PICKLE = '\ue536';
    public static final Character SHEARS = '\ue537';
    public static final Character SHULKER_SHELL = '\ue538';
    public static final Character SKULL_BANNER_PATTERN = '\ue539';
    public static final Character SLIME_BALL = '\ue53a';
    public static final Character SNOWBALL = '\ue53b';
    public static final Character SOUL_CAMPFIRE = '\ue53c';
    public static final Character SOUL_LANTERN = '\ue53d';
    public static final Character SPAWN_EGG = '\ue53e';
    public static final Character SPAWN_EGG_OVERLAY = '\ue53f';
    public static final Character SPECTRAL_ARROW = '\ue540';
    public static final Character SPIDER_EYE = '\ue541';
    public static final Character SPLASH_POTION = '\ue542';
    public static final Character SPRUCE_BOAT = '\ue543';
    public static final Character SPRUCE_CHEST_BOAT = '\ue544';
    public static final Character SPRUCE_DOOR = '\ue545';
    public static final Character SPRUCE_HANGING_SIGN = '\ue546';
    public static final Character SPRUCE_SIGN = '\ue547';
    public static final Character SPYGLASS = '\ue548';
    public static final Character SPYGLASS_MODEL = '\ue549';
    public static final Character STICK = '\ue54a';
    public static final Character STONE_AXE = '\ue54b';
    public static final Character STONE_HOE = '\ue54c';
    public static final Character STONE_PICKAXE = '\ue54d';
    public static final Character STONE_SHOVEL = '\ue54e';
    public static final Character STONE_SWORD = '\ue54f';
    public static final Character STRING = '\ue550';
    public static final Character STRUCTURE_VOID = '\ue551';
    public static final Character SUGAR = '\ue552';
    public static final Character SUGAR_CANE = '\ue553';
    public static final Character SUSPICIOUS_STEW = '\ue554';
    public static final Character SWEET_BERRIES = '\ue555';
    public static final Character TADPOLE_BUCKET = '\ue556';
    public static final Character TIPPED_ARROW_BASE = '\ue557';
    public static final Character TIPPED_ARROW_HEAD = '\ue558';
    public static final Character TNT_MINECART = '\ue559';
    public static final Character TOTEM_OF_UNDYING = '\ue55a';
    public static final Character TRIDENT = '\ue55b';
    public static final Character TROPICAL_FISH = '\ue55c';
    public static final Character TROPICAL_FISH_BUCKET = '\ue55d';
    public static final Character TURTLE_EGG = '\ue55e';
    public static final Character TURTLE_HELMET = '\ue55f';
    public static final Character WARPED_DOOR = '\ue560';
    public static final Character WARPED_FUNGUS_ON_A_STICK = '\ue561';
    public static final Character WARPED_HANGING_SIGN = '\ue562';
    public static final Character WARPED_SIGN = '\ue563';
    public static final Character WATER_BUCKET = '\ue564';
    public static final Character WHEAT = '\ue565';
    public static final Character WHEAT_SEEDS = '\ue566';
    public static final Character WHITE_CANDLE = '\ue567';
    public static final Character WHITE_DYE = '\ue568';
    public static final Character WOODEN_AXE = '\ue569';
    public static final Character WOODEN_HOE = '\ue56a';
    public static final Character WOODEN_PICKAXE = '\ue56b';
    public static final Character WOODEN_SHOVEL = '\ue56c';
    public static final Character WOODEN_SWORD = '\ue56d';
    public static final Character WRITABLE_BOOK = '\ue56e';
    public static final Character WRITTEN_BOOK = '\ue56f';
    public static final Character YELLOW_CANDLE = '\ue570';
    public static final Character YELLOW_DYE = '\ue571';
    public static final Character ANGLER_POTTERY_SHERD = '\ue5fc';
    public static final Character ARCHER_POTTERY_SHERD = '\ue5fd';
    public static final Character ARMADILLO_SCUTE = '\ue5fe';
    public static final Character ARMS_UP_POTTERY_SHERD = '\ue5ff';
    public static final Character BLADE_POTTERY_SHERD = '\ue600';
    public static final Character BOLT_ARMOR_TRIM_SMITHING_TEMPLATE = '\ue601';
    public static final Character BREEZE_ROD = '\ue602';
    public static final Character BREWER_POTTERY_SHERD = '\ue603';
    public static final Character BRUSH = '\ue604';
    public static final Character BURN_POTTERY_SHERD = '\ue605';
    public static final Character CHERRY_BOAT = '\ue606';
    public static final Character CHERRY_CHEST_BOAT = '\ue607';
    public static final Character CHERRY_DOOR = '\ue608';
    public static final Character CHERRY_HANGING_SIGN = '\ue609';
    public static final Character CHERRY_SIGN = '\ue60a';
    public static final Character COAST_ARMOR_TRIM_SMITHING_TEMPLATE = '\ue60b';
    public static final Character COPPER_DOOR = '\ue60c';
    public static final Character DANGER_POTTERY_SHERD = '\ue60d';
    public static final Character DUNE_ARMOR_TRIM_SMITHING_TEMPLATE = '\ue60e';
    public static final Character EMPTY_SLOT_AMETHYST_SHARD = '\ue60f';
    public static final Character EMPTY_SLOT_AXE = '\ue610';
    public static final Character EMPTY_SLOT_DIAMOND = '\ue611';
    public static final Character EMPTY_SLOT_EMERALD = '\ue612';
    public static final Character EMPTY_SLOT_HOE = '\ue613';
    public static final Character EMPTY_SLOT_INGOT = '\ue614';
    public static final Character EMPTY_SLOT_LAPIS_LAZULI = '\ue615';
    public static final Character EMPTY_SLOT_PICKAXE = '\ue616';
    public static final Character EMPTY_SLOT_QUARTZ = '\ue617';
    public static final Character EMPTY_SLOT_REDSTONE_DUST = '\ue618';
    public static final Character EMPTY_SLOT_SHOVEL = '\ue619';
    public static final Character EMPTY_SLOT_SMITHING_TEMPLATE_ARMOR_TRIM = '\ue61a';
    public static final Character EMPTY_SLOT_SMITHING_TEMPLATE_NETHERITE_UPGRADE = '\ue61b';
    public static final Character EMPTY_SLOT_SWORD = '\ue61c';
    public static final Character EXPLORER_POTTERY_SHERD = '\ue61d';
    public static final Character EXPOSED_COPPER_DOOR = '\ue61e';
    public static final Character EYE_ARMOR_TRIM_SMITHING_TEMPLATE = '\ue61f';
    public static final Character FLOW_ARMOR_TRIM_SMITHING_TEMPLATE = '\ue620';
    public static final Character FLOW_BANNER_PATTERN = '\ue621';
    public static final Character FLOW_POTTERY_SHERD = '\ue622';
    public static final Character FRIEND_POTTERY_SHERD = '\ue623';
    public static final Character GUSTER_BANNER_PATTERN = '\ue624';
    public static final Character GUSTER_POTTERY_SHERD = '\ue625';
    public static final Character HEARTBREAK_POTTERY_SHERD = '\ue626';
    public static final Character HEART_POTTERY_SHERD = '\ue627';
    public static final Character HOST_ARMOR_TRIM_SMITHING_TEMPLATE = '\ue628';
    public static final Character HOWL_POTTERY_SHERD = '\ue629';
    public static final Character MACE = '\ue62a';
    public static final Character MINER_POTTERY_SHERD = '\ue62b';
    public static final Character MOURNER_POTTERY_SHERD = '\ue62c';
    public static final Character MUSIC_DISC_CREATOR = '\ue62d';
    public static final Character MUSIC_DISC_CREATOR_MUSIC_BOX = '\ue62e';
    public static final Character MUSIC_DISC_PRECIPICE = '\ue62f';
    public static final Character MUSIC_DISC_RELIC = '\ue630';
    public static final Character NETHERITE_UPGRADE_SMITHING_TEMPLATE = '\ue631';
    public static final Character OMINOUS_BOTTLE = '\ue632';
    public static final Character OMINOUS_TRIAL_KEY = '\ue633';
    public static final Character OXIDIZED_COPPER_DOOR = '\ue634';
    public static final Character PINK_PETALS = '\ue635';
    public static final Character PITCHER_PLANT = '\ue636';
    public static final Character PITCHER_POD = '\ue637';
    public static final Character PLENTY_POTTERY_SHERD = '\ue638';
    public static final Character PRIZE_POTTERY_SHERD = '\ue639';
    public static final Character RAISER_ARMOR_TRIM_SMITHING_TEMPLATE = '\ue63a';
    public static final Character RIB_ARMOR_TRIM_SMITHING_TEMPLATE = '\ue63b';
    public static final Character SCRAPE_POTTERY_SHERD = '\ue63c';
    public static final Character SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE = '\ue63d';
    public static final Character SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE = '\ue63e';
    public static final Character SHEAF_POTTERY_SHERD = '\ue63f';
    public static final Character SHELTER_POTTERY_SHERD = '\ue640';
    public static final Character SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE = '\ue641';
    public static final Character SKULL_POTTERY_SHERD = '\ue642';
    public static final Character SNIFFER_EGG = '\ue643';
    public static final Character SNORT_POTTERY_SHERD = '\ue644';
    public static final Character SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE = '\ue645';
    public static final Character SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE = '\ue646';
    public static final Character TIDE_ARMOR_TRIM_SMITHING_TEMPLATE = '\ue647';
    public static final Character TORCHFLOWER_SEEDS = '\ue648';
    public static final Character TRIAL_KEY = '\ue649';
    public static final Character TURTLE_SCUTE = '\ue64a';
    public static final Character VEX_ARMOR_TRIM_SMITHING_TEMPLATE = '\ue64b';
    public static final Character WARD_ARMOR_TRIM_SMITHING_TEMPLATE = '\ue64c';
    public static final Character WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE = '\ue64d';
    public static final Character WEATHERED_COPPER_DOOR = '\ue64e';
    public static final Character WILD_ARMOR_TRIM_SMITHING_TEMPLATE = '\ue64f';
    public static final Character WIND_CHARGE = '\ue650';
    public static final Character WOLF_ARMOR = '\ue651';
    public static final Character WOLF_ARMOR_OVERLAY = '\ue652';

    public static @Nullable Character fromMaterial(Material material) {
        if (material == Material.ACACIA_BOAT) return ACACIA_BOAT;
        if (material == Material.ACACIA_CHEST_BOAT) return ACACIA_CHEST_BOAT;
        if (material == Material.ACACIA_DOOR) return ACACIA_DOOR;
        if (material == Material.ACACIA_HANGING_SIGN) return ACACIA_HANGING_SIGN;
        if (material == Material.ACACIA_SIGN) return ACACIA_SIGN;
        if (material == Material.AMETHYST_SHARD) return AMETHYST_SHARD;
        if (material == Material.APPLE) return APPLE;
        if (material == Material.ARMOR_STAND) return ARMOR_STAND;
        if (material == Material.ARROW) return ARROW;
        if (material == Material.AXOLOTL_BUCKET) return AXOLOTL_BUCKET;
        if (material == Material.BAKED_POTATO) return BAKED_POTATO;
        if (material == Material.BAMBOO) return BAMBOO;
        if (material == Material.BAMBOO_CHEST_RAFT) return BAMBOO_CHEST_RAFT;
        if (material == Material.BAMBOO_DOOR) return BAMBOO_DOOR;
        if (material == Material.BAMBOO_HANGING_SIGN) return BAMBOO_HANGING_SIGN;
        if (material == Material.BAMBOO_RAFT) return BAMBOO_RAFT;
        if (material == Material.BAMBOO_SIGN) return BAMBOO_SIGN;
        if (material == Material.BARRIER) return BARRIER;
        if (material == Material.BEEF) return BEEF;
        if (material == Material.BEETROOT) return BEETROOT;
        if (material == Material.BEETROOT_SEEDS) return BEETROOT_SEEDS;
        if (material == Material.BEETROOT_SOUP) return BEETROOT_SOUP;
        if (material == Material.BELL) return BELL;
        if (material == Material.BIRCH_BOAT) return BIRCH_BOAT;
        if (material == Material.BIRCH_CHEST_BOAT) return BIRCH_CHEST_BOAT;
        if (material == Material.BIRCH_DOOR) return BIRCH_DOOR;
        if (material == Material.BIRCH_HANGING_SIGN) return BIRCH_HANGING_SIGN;
        if (material == Material.BIRCH_SIGN) return BIRCH_SIGN;
        if (material == Material.BLACK_CANDLE) return BLACK_CANDLE;
        if (material == Material.BLACK_DYE) return BLACK_DYE;
        if (material == Material.BLAZE_POWDER) return BLAZE_POWDER;
        if (material == Material.BLAZE_ROD) return BLAZE_ROD;
        if (material == Material.BLUE_CANDLE) return BLUE_CANDLE;
        if (material == Material.BLUE_DYE) return BLUE_DYE;
        if (material == Material.BONE) return BONE;
        if (material == Material.BONE_MEAL) return BONE_MEAL;
        if (material == Material.BOOK) return BOOK;
        if (material == Material.BOW) return BOW;
        if (material == Material.BOWL) return BOWL;
        if (material == Material.BREAD) return BREAD;
        if (material == Material.BREWING_STAND) return BREWING_STAND;
        if (material == Material.BRICK) return BRICK;
        if (material == Material.BROWN_CANDLE) return BROWN_CANDLE;
        if (material == Material.BROWN_DYE) return BROWN_DYE;
        if (material == Material.BUCKET) return BUCKET;
        if (material == Material.BUNDLE) return BUNDLE;
        if (material == Material.CAKE) return CAKE;
        if (material == Material.CAMPFIRE) return CAMPFIRE;
        if (material == Material.CANDLE) return CANDLE;
        if (material == Material.CARROT) return CARROT;
        if (material == Material.CARROT_ON_A_STICK) return CARROT_ON_A_STICK;
        if (material == Material.CAULDRON) return CAULDRON;
        if (material == Material.CHAIN) return CHAIN;
        if (material == Material.CHAINMAIL_BOOTS) return CHAINMAIL_BOOTS;
        if (material == Material.CHAINMAIL_CHESTPLATE) return CHAINMAIL_CHESTPLATE;
        if (material == Material.CHAINMAIL_HELMET) return CHAINMAIL_HELMET;
        if (material == Material.CHAINMAIL_LEGGINGS) return CHAINMAIL_LEGGINGS;
        if (material == Material.CHARCOAL) return CHARCOAL;
        if (material == Material.CHEST_MINECART) return CHEST_MINECART;
        if (material == Material.CHICKEN) return CHICKEN;
        if (material == Material.CHORUS_FRUIT) return CHORUS_FRUIT;
        if (material == Material.CLAY_BALL) return CLAY_BALL;
        if (material == Material.COAL) return COAL;
        if (material == Material.COCOA_BEANS) return COCOA_BEANS;
        if (material == Material.COD) return COD;
        if (material == Material.COD_BUCKET) return COD_BUCKET;
        if (material == Material.COMMAND_BLOCK_MINECART) return COMMAND_BLOCK_MINECART;
        if (material == Material.COMPARATOR) return COMPARATOR;
        if (material == Material.COOKED_BEEF) return COOKED_BEEF;
        if (material == Material.COOKED_CHICKEN) return COOKED_CHICKEN;
        if (material == Material.COOKED_COD) return COOKED_COD;
        if (material == Material.COOKED_MUTTON) return COOKED_MUTTON;
        if (material == Material.COOKED_PORKCHOP) return COOKED_PORKCHOP;
        if (material == Material.COOKED_RABBIT) return COOKED_RABBIT;
        if (material == Material.COOKED_SALMON) return COOKED_SALMON;
        if (material == Material.COOKIE) return COOKIE;
        if (material == Material.COPPER_INGOT) return COPPER_INGOT;
        if (material == Material.CREEPER_BANNER_PATTERN) return CREEPER_BANNER_PATTERN;
        if (material == Material.CRIMSON_DOOR) return CRIMSON_DOOR;
        if (material == Material.CRIMSON_HANGING_SIGN) return CRIMSON_HANGING_SIGN;
        if (material == Material.CRIMSON_SIGN) return CRIMSON_SIGN;
        if (material == Material.CYAN_CANDLE) return CYAN_CANDLE;
        if (material == Material.CYAN_DYE) return CYAN_DYE;
        if (material == Material.DARK_OAK_BOAT) return DARK_OAK_BOAT;
        if (material == Material.DARK_OAK_CHEST_BOAT) return DARK_OAK_CHEST_BOAT;
        if (material == Material.DARK_OAK_DOOR) return DARK_OAK_DOOR;
        if (material == Material.DARK_OAK_HANGING_SIGN) return DARK_OAK_HANGING_SIGN;
        if (material == Material.DARK_OAK_SIGN) return DARK_OAK_SIGN;
        if (material == Material.DIAMOND) return DIAMOND;
        if (material == Material.DIAMOND_AXE) return DIAMOND_AXE;
        if (material == Material.DIAMOND_BOOTS) return DIAMOND_BOOTS;
        if (material == Material.DIAMOND_CHESTPLATE) return DIAMOND_CHESTPLATE;
        if (material == Material.DIAMOND_HELMET) return DIAMOND_HELMET;
        if (material == Material.DIAMOND_HOE) return DIAMOND_HOE;
        if (material == Material.DIAMOND_HORSE_ARMOR) return DIAMOND_HORSE_ARMOR;
        if (material == Material.DIAMOND_LEGGINGS) return DIAMOND_LEGGINGS;
        if (material == Material.DIAMOND_PICKAXE) return DIAMOND_PICKAXE;
        if (material == Material.DIAMOND_SHOVEL) return DIAMOND_SHOVEL;
        if (material == Material.DIAMOND_SWORD) return DIAMOND_SWORD;
        if (material == Material.DISC_FRAGMENT_5) return DISC_FRAGMENT_5;
        if (material == Material.DRAGON_BREATH) return DRAGON_BREATH;
        if (material == Material.DRIED_KELP) return DRIED_KELP;
        if (material == Material.ECHO_SHARD) return ECHO_SHARD;
        if (material == Material.EGG) return EGG;
        if (material == Material.ELYTRA) return ELYTRA;
        if (material == Material.EMERALD) return EMERALD;
        if (material == Material.ENCHANTED_BOOK) return ENCHANTED_BOOK;
        if (material == Material.ENDER_EYE) return ENDER_EYE;
        if (material == Material.ENDER_PEARL) return ENDER_PEARL;
        if (material == Material.END_CRYSTAL) return END_CRYSTAL;
        if (material == Material.EXPERIENCE_BOTTLE) return EXPERIENCE_BOTTLE;
        if (material == Material.FEATHER) return FEATHER;
        if (material == Material.FERMENTED_SPIDER_EYE) return FERMENTED_SPIDER_EYE;
        if (material == Material.FILLED_MAP) return FILLED_MAP;
        if (material == Material.FIREWORK_ROCKET) return FIREWORK_ROCKET;
        if (material == Material.FIREWORK_STAR) return FIREWORK_STAR;
        if (material == Material.FIRE_CHARGE) return FIRE_CHARGE;
        if (material == Material.FISHING_ROD) return FISHING_ROD;
        if (material == Material.FLINT) return FLINT;
        if (material == Material.FLINT_AND_STEEL) return FLINT_AND_STEEL;
        if (material == Material.FLOWER_BANNER_PATTERN) return FLOWER_BANNER_PATTERN;
        if (material == Material.FLOWER_POT) return FLOWER_POT;
        if (material == Material.FURNACE_MINECART) return FURNACE_MINECART;
        if (material == Material.GHAST_TEAR) return GHAST_TEAR;
        if (material == Material.GLASS_BOTTLE) return GLASS_BOTTLE;
        if (material == Material.GLISTERING_MELON_SLICE) return GLISTERING_MELON_SLICE;
        if (material == Material.GLOBE_BANNER_PATTERN) return GLOBE_BANNER_PATTERN;
        if (material == Material.GLOWSTONE_DUST) return GLOWSTONE_DUST;
        if (material == Material.GLOW_BERRIES) return GLOW_BERRIES;
        if (material == Material.GLOW_INK_SAC) return GLOW_INK_SAC;
        if (material == Material.GLOW_ITEM_FRAME) return GLOW_ITEM_FRAME;
        if (material == Material.GOAT_HORN) return GOAT_HORN;
        if (material == Material.GOLDEN_APPLE) return GOLDEN_APPLE;
        if (material == Material.GOLDEN_AXE) return GOLDEN_AXE;
        if (material == Material.GOLDEN_BOOTS) return GOLDEN_BOOTS;
        if (material == Material.GOLDEN_CARROT) return GOLDEN_CARROT;
        if (material == Material.GOLDEN_CHESTPLATE) return GOLDEN_CHESTPLATE;
        if (material == Material.GOLDEN_HELMET) return GOLDEN_HELMET;
        if (material == Material.GOLDEN_HOE) return GOLDEN_HOE;
        if (material == Material.GOLDEN_HORSE_ARMOR) return GOLDEN_HORSE_ARMOR;
        if (material == Material.GOLDEN_LEGGINGS) return GOLDEN_LEGGINGS;
        if (material == Material.GOLDEN_PICKAXE) return GOLDEN_PICKAXE;
        if (material == Material.GOLDEN_SHOVEL) return GOLDEN_SHOVEL;
        if (material == Material.GOLDEN_SWORD) return GOLDEN_SWORD;
        if (material == Material.GOLD_INGOT) return GOLD_INGOT;
        if (material == Material.GOLD_NUGGET) return GOLD_NUGGET;
        if (material == Material.GRAY_CANDLE) return GRAY_CANDLE;
        if (material == Material.GRAY_DYE) return GRAY_DYE;
        if (material == Material.GREEN_CANDLE) return GREEN_CANDLE;
        if (material == Material.GREEN_DYE) return GREEN_DYE;
        if (material == Material.GUNPOWDER) return GUNPOWDER;
        if (material == Material.HEART_OF_THE_SEA) return HEART_OF_THE_SEA;
        if (material == Material.HONEYCOMB) return HONEYCOMB;
        if (material == Material.HONEY_BOTTLE) return HONEY_BOTTLE;
        if (material == Material.HOPPER) return HOPPER;
        if (material == Material.HOPPER_MINECART) return HOPPER_MINECART;
        if (material == Material.INK_SAC) return INK_SAC;
        if (material == Material.IRON_AXE) return IRON_AXE;
        if (material == Material.IRON_BOOTS) return IRON_BOOTS;
        if (material == Material.IRON_CHESTPLATE) return IRON_CHESTPLATE;
        if (material == Material.IRON_DOOR) return IRON_DOOR;
        if (material == Material.IRON_HELMET) return IRON_HELMET;
        if (material == Material.IRON_HOE) return IRON_HOE;
        if (material == Material.IRON_HORSE_ARMOR) return IRON_HORSE_ARMOR;
        if (material == Material.IRON_INGOT) return IRON_INGOT;
        if (material == Material.IRON_LEGGINGS) return IRON_LEGGINGS;
        if (material == Material.IRON_NUGGET) return IRON_NUGGET;
        if (material == Material.IRON_PICKAXE) return IRON_PICKAXE;
        if (material == Material.IRON_SHOVEL) return IRON_SHOVEL;
        if (material == Material.IRON_SWORD) return IRON_SWORD;
        if (material == Material.ITEM_FRAME) return ITEM_FRAME;
        if (material == Material.JUNGLE_BOAT) return JUNGLE_BOAT;
        if (material == Material.JUNGLE_CHEST_BOAT) return JUNGLE_CHEST_BOAT;
        if (material == Material.JUNGLE_DOOR) return JUNGLE_DOOR;
        if (material == Material.JUNGLE_HANGING_SIGN) return JUNGLE_HANGING_SIGN;
        if (material == Material.JUNGLE_SIGN) return JUNGLE_SIGN;
        if (material == Material.KELP) return KELP;
        if (material == Material.KNOWLEDGE_BOOK) return KNOWLEDGE_BOOK;
        if (material == Material.LANTERN) return LANTERN;
        if (material == Material.LAPIS_LAZULI) return LAPIS_LAZULI;
        if (material == Material.LAVA_BUCKET) return LAVA_BUCKET;
        if (material == Material.LEAD) return LEAD;
        if (material == Material.LEATHER) return LEATHER;
        if (material == Material.LEATHER_BOOTS) return LEATHER_BOOTS;
        if (material == Material.LEATHER_CHESTPLATE) return LEATHER_CHESTPLATE;
        if (material == Material.LEATHER_HELMET) return LEATHER_HELMET;
        if (material == Material.LEATHER_HORSE_ARMOR) return LEATHER_HORSE_ARMOR;
        if (material == Material.LEATHER_LEGGINGS) return LEATHER_LEGGINGS;
        if (material == Material.LIGHT) return LIGHT;
        if (material == Material.LIGHT_BLUE_CANDLE) return LIGHT_BLUE_CANDLE;
        if (material == Material.LIGHT_BLUE_DYE) return LIGHT_BLUE_DYE;
        if (material == Material.LIGHT_GRAY_CANDLE) return LIGHT_GRAY_CANDLE;
        if (material == Material.LIGHT_GRAY_DYE) return LIGHT_GRAY_DYE;
        if (material == Material.LIME_CANDLE) return LIME_CANDLE;
        if (material == Material.LIME_DYE) return LIME_DYE;
        if (material == Material.LINGERING_POTION) return LINGERING_POTION;
        if (material == Material.MAGENTA_CANDLE) return MAGENTA_CANDLE;
        if (material == Material.MAGENTA_DYE) return MAGENTA_DYE;
        if (material == Material.MAGMA_CREAM) return MAGMA_CREAM;
        if (material == Material.MANGROVE_BOAT) return MANGROVE_BOAT;
        if (material == Material.MANGROVE_CHEST_BOAT) return MANGROVE_CHEST_BOAT;
        if (material == Material.MANGROVE_DOOR) return MANGROVE_DOOR;
        if (material == Material.MANGROVE_HANGING_SIGN) return MANGROVE_HANGING_SIGN;
        if (material == Material.MANGROVE_PROPAGULE) return MANGROVE_PROPAGULE;
        if (material == Material.MANGROVE_SIGN) return MANGROVE_SIGN;
        if (material == Material.MAP) return MAP;
        if (material == Material.MELON_SEEDS) return MELON_SEEDS;
        if (material == Material.MELON_SLICE) return MELON_SLICE;
        if (material == Material.MILK_BUCKET) return MILK_BUCKET;
        if (material == Material.MINECART) return MINECART;
        if (material == Material.MOJANG_BANNER_PATTERN) return MOJANG_BANNER_PATTERN;
        if (material == Material.MUSHROOM_STEW) return MUSHROOM_STEW;
        if (material == Material.MUSIC_DISC_11) return MUSIC_DISC_11;
        if (material == Material.MUSIC_DISC_13) return MUSIC_DISC_13;
        if (material == Material.MUSIC_DISC_5) return MUSIC_DISC_5;
        if (material == Material.MUSIC_DISC_BLOCKS) return MUSIC_DISC_BLOCKS;
        if (material == Material.MUSIC_DISC_CAT) return MUSIC_DISC_CAT;
        if (material == Material.MUSIC_DISC_CHIRP) return MUSIC_DISC_CHIRP;
        if (material == Material.MUSIC_DISC_FAR) return MUSIC_DISC_FAR;
        if (material == Material.MUSIC_DISC_MALL) return MUSIC_DISC_MALL;
        if (material == Material.MUSIC_DISC_MELLOHI) return MUSIC_DISC_MELLOHI;
        if (material == Material.MUSIC_DISC_OTHERSIDE) return MUSIC_DISC_OTHERSIDE;
        if (material == Material.MUSIC_DISC_PIGSTEP) return MUSIC_DISC_PIGSTEP;
        if (material == Material.MUSIC_DISC_STAL) return MUSIC_DISC_STAL;
        if (material == Material.MUSIC_DISC_STRAD) return MUSIC_DISC_STRAD;
        if (material == Material.MUSIC_DISC_WAIT) return MUSIC_DISC_WAIT;
        if (material == Material.MUSIC_DISC_WARD) return MUSIC_DISC_WARD;
        if (material == Material.MUTTON) return MUTTON;
        if (material == Material.NAME_TAG) return NAME_TAG;
        if (material == Material.NAUTILUS_SHELL) return NAUTILUS_SHELL;
        if (material == Material.NETHERITE_AXE) return NETHERITE_AXE;
        if (material == Material.NETHERITE_BOOTS) return NETHERITE_BOOTS;
        if (material == Material.NETHERITE_CHESTPLATE) return NETHERITE_CHESTPLATE;
        if (material == Material.NETHERITE_HELMET) return NETHERITE_HELMET;
        if (material == Material.NETHERITE_HOE) return NETHERITE_HOE;
        if (material == Material.NETHERITE_INGOT) return NETHERITE_INGOT;
        if (material == Material.NETHERITE_LEGGINGS) return NETHERITE_LEGGINGS;
        if (material == Material.NETHERITE_PICKAXE) return NETHERITE_PICKAXE;
        if (material == Material.NETHERITE_SCRAP) return NETHERITE_SCRAP;
        if (material == Material.NETHERITE_SHOVEL) return NETHERITE_SHOVEL;
        if (material == Material.NETHERITE_SWORD) return NETHERITE_SWORD;
        if (material == Material.NETHER_BRICK) return NETHER_BRICK;
        if (material == Material.NETHER_SPROUTS) return NETHER_SPROUTS;
        if (material == Material.NETHER_STAR) return NETHER_STAR;
        if (material == Material.NETHER_WART) return NETHER_WART;
        if (material == Material.OAK_BOAT) return OAK_BOAT;
        if (material == Material.OAK_CHEST_BOAT) return OAK_CHEST_BOAT;
        if (material == Material.OAK_DOOR) return OAK_DOOR;
        if (material == Material.OAK_HANGING_SIGN) return OAK_HANGING_SIGN;
        if (material == Material.OAK_SIGN) return OAK_SIGN;
        if (material == Material.ORANGE_CANDLE) return ORANGE_CANDLE;
        if (material == Material.ORANGE_DYE) return ORANGE_DYE;
        if (material == Material.PAINTING) return PAINTING;
        if (material == Material.PAPER) return PAPER;
        if (material == Material.PHANTOM_MEMBRANE) return PHANTOM_MEMBRANE;
        if (material == Material.PIGLIN_BANNER_PATTERN) return PIGLIN_BANNER_PATTERN;
        if (material == Material.PINK_CANDLE) return PINK_CANDLE;
        if (material == Material.PINK_DYE) return PINK_DYE;
        if (material == Material.POINTED_DRIPSTONE) return POINTED_DRIPSTONE;
        if (material == Material.POISONOUS_POTATO) return POISONOUS_POTATO;
        if (material == Material.POPPED_CHORUS_FRUIT) return POPPED_CHORUS_FRUIT;
        if (material == Material.PORKCHOP) return PORKCHOP;
        if (material == Material.POTATO) return POTATO;
        if (material == Material.POTION) return POTION;
        if (material == Material.POWDER_SNOW_BUCKET) return POWDER_SNOW_BUCKET;
        if (material == Material.PRISMARINE_CRYSTALS) return PRISMARINE_CRYSTALS;
        if (material == Material.PRISMARINE_SHARD) return PRISMARINE_SHARD;
        if (material == Material.PUFFERFISH) return PUFFERFISH;
        if (material == Material.PUFFERFISH_BUCKET) return PUFFERFISH_BUCKET;
        if (material == Material.PUMPKIN_PIE) return PUMPKIN_PIE;
        if (material == Material.PUMPKIN_SEEDS) return PUMPKIN_SEEDS;
        if (material == Material.PURPLE_CANDLE) return PURPLE_CANDLE;
        if (material == Material.PURPLE_DYE) return PURPLE_DYE;
        if (material == Material.QUARTZ) return QUARTZ;
        if (material == Material.RABBIT) return RABBIT;
        if (material == Material.RABBIT_FOOT) return RABBIT_FOOT;
        if (material == Material.RABBIT_HIDE) return RABBIT_HIDE;
        if (material == Material.RABBIT_STEW) return RABBIT_STEW;
        if (material == Material.RAW_COPPER) return RAW_COPPER;
        if (material == Material.RAW_GOLD) return RAW_GOLD;
        if (material == Material.RAW_IRON) return RAW_IRON;
        if (material == Material.REDSTONE) return REDSTONE;
        if (material == Material.RED_CANDLE) return RED_CANDLE;
        if (material == Material.RED_DYE) return RED_DYE;
        if (material == Material.REPEATER) return REPEATER;
        if (material == Material.ROTTEN_FLESH) return ROTTEN_FLESH;
        if (material == Material.SADDLE) return SADDLE;
        if (material == Material.SALMON) return SALMON;
        if (material == Material.SALMON_BUCKET) return SALMON_BUCKET;
        if (material == Material.SEAGRASS) return SEAGRASS;
        if (material == Material.SEA_PICKLE) return SEA_PICKLE;
        if (material == Material.SHEARS) return SHEARS;
        if (material == Material.SHULKER_SHELL) return SHULKER_SHELL;
        if (material == Material.SKULL_BANNER_PATTERN) return SKULL_BANNER_PATTERN;
        if (material == Material.SLIME_BALL) return SLIME_BALL;
        if (material == Material.SNOWBALL) return SNOWBALL;
        if (material == Material.SOUL_CAMPFIRE) return SOUL_CAMPFIRE;
        if (material == Material.SOUL_LANTERN) return SOUL_LANTERN;
        if (material == Material.SPECTRAL_ARROW) return SPECTRAL_ARROW;
        if (material == Material.SPIDER_EYE) return SPIDER_EYE;
        if (material == Material.SPLASH_POTION) return SPLASH_POTION;
        if (material == Material.SPRUCE_BOAT) return SPRUCE_BOAT;
        if (material == Material.SPRUCE_CHEST_BOAT) return SPRUCE_CHEST_BOAT;
        if (material == Material.SPRUCE_DOOR) return SPRUCE_DOOR;
        if (material == Material.SPRUCE_HANGING_SIGN) return SPRUCE_HANGING_SIGN;
        if (material == Material.SPRUCE_SIGN) return SPRUCE_SIGN;
        if (material == Material.SPYGLASS) return SPYGLASS;
        if (material == Material.STICK) return STICK;
        if (material == Material.STONE_AXE) return STONE_AXE;
        if (material == Material.STONE_HOE) return STONE_HOE;
        if (material == Material.STONE_PICKAXE) return STONE_PICKAXE;
        if (material == Material.STONE_SHOVEL) return STONE_SHOVEL;
        if (material == Material.STONE_SWORD) return STONE_SWORD;
        if (material == Material.STRING) return STRING;
        if (material == Material.STRUCTURE_VOID) return STRUCTURE_VOID;
        if (material == Material.SUGAR) return SUGAR;
        if (material == Material.SUGAR_CANE) return SUGAR_CANE;
        if (material == Material.SUSPICIOUS_STEW) return SUSPICIOUS_STEW;
        if (material == Material.SWEET_BERRIES) return SWEET_BERRIES;
        if (material == Material.TADPOLE_BUCKET) return TADPOLE_BUCKET;
        if (material == Material.TNT_MINECART) return TNT_MINECART;
        if (material == Material.TOTEM_OF_UNDYING) return TOTEM_OF_UNDYING;
        if (material == Material.TRIDENT) return TRIDENT;
        if (material == Material.TROPICAL_FISH) return TROPICAL_FISH;
        if (material == Material.TROPICAL_FISH_BUCKET) return TROPICAL_FISH_BUCKET;
        if (material == Material.TURTLE_EGG) return TURTLE_EGG;
        if (material == Material.TURTLE_HELMET) return TURTLE_HELMET;
        if (material == Material.WARPED_DOOR) return WARPED_DOOR;
        if (material == Material.WARPED_FUNGUS_ON_A_STICK) return WARPED_FUNGUS_ON_A_STICK;
        if (material == Material.WARPED_HANGING_SIGN) return WARPED_HANGING_SIGN;
        if (material == Material.WARPED_SIGN) return WARPED_SIGN;
        if (material == Material.WATER_BUCKET) return WATER_BUCKET;
        if (material == Material.WHEAT) return WHEAT;
        if (material == Material.WHEAT_SEEDS) return WHEAT_SEEDS;
        if (material == Material.WHITE_CANDLE) return WHITE_CANDLE;
        if (material == Material.WHITE_DYE) return WHITE_DYE;
        if (material == Material.WOODEN_AXE) return WOODEN_AXE;
        if (material == Material.WOODEN_HOE) return WOODEN_HOE;
        if (material == Material.WOODEN_PICKAXE) return WOODEN_PICKAXE;
        if (material == Material.WOODEN_SHOVEL) return WOODEN_SHOVEL;
        if (material == Material.WOODEN_SWORD) return WOODEN_SWORD;
        if (material == Material.WRITABLE_BOOK) return WRITABLE_BOOK;
        if (material == Material.WRITTEN_BOOK) return WRITTEN_BOOK;
        if (material == Material.YELLOW_CANDLE) return YELLOW_CANDLE;
        if (material == Material.YELLOW_DYE) return YELLOW_DYE;
        if (material == Material.ANGLER_POTTERY_SHERD) return ANGLER_POTTERY_SHERD;
        if (material == Material.ARCHER_POTTERY_SHERD) return ARCHER_POTTERY_SHERD;
        if (material == Material.ARMADILLO_SCUTE) return ARMADILLO_SCUTE;
        if (material == Material.ARMS_UP_POTTERY_SHERD) return ARMS_UP_POTTERY_SHERD;
        if (material == Material.BLADE_POTTERY_SHERD) return BLADE_POTTERY_SHERD;
        if (material == Material.BOLT_ARMOR_TRIM_SMITHING_TEMPLATE) return BOLT_ARMOR_TRIM_SMITHING_TEMPLATE;
        if (material == Material.BREEZE_ROD) return BREEZE_ROD;
        if (material == Material.BREWER_POTTERY_SHERD) return BREWER_POTTERY_SHERD;
        if (material == Material.BRUSH) return BRUSH;
        if (material == Material.BURN_POTTERY_SHERD) return BURN_POTTERY_SHERD;
        if (material == Material.CHERRY_BOAT) return CHERRY_BOAT;
        if (material == Material.CHERRY_CHEST_BOAT) return CHERRY_CHEST_BOAT;
        if (material == Material.CHERRY_DOOR) return CHERRY_DOOR;
        if (material == Material.CHERRY_HANGING_SIGN) return CHERRY_HANGING_SIGN;
        if (material == Material.CHERRY_SIGN) return CHERRY_SIGN;
        if (material == Material.COAST_ARMOR_TRIM_SMITHING_TEMPLATE) return COAST_ARMOR_TRIM_SMITHING_TEMPLATE;
        if (material == Material.COPPER_DOOR) return COPPER_DOOR;
        if (material == Material.DANGER_POTTERY_SHERD) return DANGER_POTTERY_SHERD;
        if (material == Material.DUNE_ARMOR_TRIM_SMITHING_TEMPLATE) return DUNE_ARMOR_TRIM_SMITHING_TEMPLATE;
        if (material == Material.EXPLORER_POTTERY_SHERD) return EXPLORER_POTTERY_SHERD;
        if (material == Material.EXPOSED_COPPER_DOOR) return EXPOSED_COPPER_DOOR;
        if (material == Material.EYE_ARMOR_TRIM_SMITHING_TEMPLATE) return EYE_ARMOR_TRIM_SMITHING_TEMPLATE;
        if (material == Material.FLOW_ARMOR_TRIM_SMITHING_TEMPLATE) return FLOW_ARMOR_TRIM_SMITHING_TEMPLATE;
        if (material == Material.FLOW_BANNER_PATTERN) return FLOW_BANNER_PATTERN;
        if (material == Material.FLOW_POTTERY_SHERD) return FLOW_POTTERY_SHERD;
        if (material == Material.FRIEND_POTTERY_SHERD) return FRIEND_POTTERY_SHERD;
        if (material == Material.GUSTER_BANNER_PATTERN) return GUSTER_BANNER_PATTERN;
        if (material == Material.GUSTER_POTTERY_SHERD) return GUSTER_POTTERY_SHERD;
        if (material == Material.HEARTBREAK_POTTERY_SHERD) return HEARTBREAK_POTTERY_SHERD;
        if (material == Material.HEART_POTTERY_SHERD) return HEART_POTTERY_SHERD;
        if (material == Material.HOST_ARMOR_TRIM_SMITHING_TEMPLATE) return HOST_ARMOR_TRIM_SMITHING_TEMPLATE;
        if (material == Material.HOWL_POTTERY_SHERD) return HOWL_POTTERY_SHERD;
        if (material == Material.MACE) return MACE;
        if (material == Material.MINER_POTTERY_SHERD) return MINER_POTTERY_SHERD;
        if (material == Material.MOURNER_POTTERY_SHERD) return MOURNER_POTTERY_SHERD;
        if (material == Material.MUSIC_DISC_CREATOR) return MUSIC_DISC_CREATOR;
        if (material == Material.MUSIC_DISC_CREATOR_MUSIC_BOX) return MUSIC_DISC_CREATOR_MUSIC_BOX;
        if (material == Material.MUSIC_DISC_PRECIPICE) return MUSIC_DISC_PRECIPICE;
        if (material == Material.MUSIC_DISC_RELIC) return MUSIC_DISC_RELIC;
        if (material == Material.NETHERITE_UPGRADE_SMITHING_TEMPLATE) return NETHERITE_UPGRADE_SMITHING_TEMPLATE;
        if (material == Material.OMINOUS_BOTTLE) return OMINOUS_BOTTLE;
        if (material == Material.OMINOUS_TRIAL_KEY) return OMINOUS_TRIAL_KEY;
        if (material == Material.OXIDIZED_COPPER_DOOR) return OXIDIZED_COPPER_DOOR;
        if (material == Material.PINK_PETALS) return PINK_PETALS;
        if (material == Material.PITCHER_PLANT) return PITCHER_PLANT;
        if (material == Material.PITCHER_POD) return PITCHER_POD;
        if (material == Material.PLENTY_POTTERY_SHERD) return PLENTY_POTTERY_SHERD;
        if (material == Material.PRIZE_POTTERY_SHERD) return PRIZE_POTTERY_SHERD;
        if (material == Material.RAISER_ARMOR_TRIM_SMITHING_TEMPLATE) return RAISER_ARMOR_TRIM_SMITHING_TEMPLATE;
        if (material == Material.RIB_ARMOR_TRIM_SMITHING_TEMPLATE) return RIB_ARMOR_TRIM_SMITHING_TEMPLATE;
        if (material == Material.SCRAPE_POTTERY_SHERD) return SCRAPE_POTTERY_SHERD;
        if (material == Material.SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE) return SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE;
        if (material == Material.SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE) return SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE;
        if (material == Material.SHEAF_POTTERY_SHERD) return SHEAF_POTTERY_SHERD;
        if (material == Material.SHELTER_POTTERY_SHERD) return SHELTER_POTTERY_SHERD;
        if (material == Material.SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE) return SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE;
        if (material == Material.SKULL_POTTERY_SHERD) return SKULL_POTTERY_SHERD;
        if (material == Material.SNIFFER_EGG) return SNIFFER_EGG;
        if (material == Material.SNORT_POTTERY_SHERD) return SNORT_POTTERY_SHERD;
        if (material == Material.SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE) return SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE;
        if (material == Material.SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE) return SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE;
        if (material == Material.TIDE_ARMOR_TRIM_SMITHING_TEMPLATE) return TIDE_ARMOR_TRIM_SMITHING_TEMPLATE;
        if (material == Material.TORCHFLOWER_SEEDS) return TORCHFLOWER_SEEDS;
        if (material == Material.TRIAL_KEY) return TRIAL_KEY;
        if (material == Material.TURTLE_SCUTE) return TURTLE_SCUTE;
        if (material == Material.VEX_ARMOR_TRIM_SMITHING_TEMPLATE) return VEX_ARMOR_TRIM_SMITHING_TEMPLATE;
        if (material == Material.WARD_ARMOR_TRIM_SMITHING_TEMPLATE) return WARD_ARMOR_TRIM_SMITHING_TEMPLATE;
        if (material == Material.WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE) return WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE;
        if (material == Material.WEATHERED_COPPER_DOOR) return WEATHERED_COPPER_DOOR;
        if (material == Material.WILD_ARMOR_TRIM_SMITHING_TEMPLATE) return WILD_ARMOR_TRIM_SMITHING_TEMPLATE;
        if (material == Material.WIND_CHARGE) return WIND_CHARGE;
        if (material == Material.WOLF_ARMOR) return WOLF_ARMOR;
        return null;
    }

    public static Character fromMaterialElse(Material material, Character elseCharacter) {
        Character current = fromMaterial(material);
        return current != null ? current : elseCharacter;
    }
}