package com.notmarra.notlib.font;

import javax.annotation.Nullable;

import org.bukkit.Material;

public class NotFontBlock {
    public static final Character ACACIA_DOOR_BOTTOM = '\ue000';
    public static final Character ACACIA_DOOR_TOP = '\ue001';
    public static final Character ACACIA_LEAVES = '\ue002';
    public static final Character ACACIA_LOG = '\ue003';
    public static final Character ACACIA_LOG_TOP = '\ue004';
    public static final Character ACACIA_PLANKS = '\ue005';
    public static final Character ACACIA_SAPLING = '\ue006';
    public static final Character ACACIA_TRAPDOOR = '\ue007';
    public static final Character ACTIVATOR_RAIL = '\ue008';
    public static final Character ACTIVATOR_RAIL_ON = '\ue009';
    public static final Character ALLIUM = '\ue00a';
    public static final Character AMETHYST_BLOCK = '\ue00b';
    public static final Character AMETHYST_CLUSTER = '\ue00c';
    public static final Character ANCIENT_DEBRIS_SIDE = '\ue00d';
    public static final Character ANCIENT_DEBRIS_TOP = '\ue00e';
    public static final Character ANDESITE = '\ue00f';
    public static final Character ANVIL = '\ue010';
    public static final Character ANVIL_TOP = '\ue011';
    public static final Character ATTACHED_MELON_STEM = '\ue012';
    public static final Character ATTACHED_PUMPKIN_STEM = '\ue013';
    public static final Character AZALEA_LEAVES = '\ue014';
    public static final Character AZALEA_PLANT = '\ue015';
    public static final Character AZALEA_SIDE = '\ue016';
    public static final Character AZALEA_TOP = '\ue017';
    public static final Character AZURE_BLUET = '\ue018';
    public static final Character BAMBOO_BLOCK = '\ue019';
    public static final Character BAMBOO_BLOCK_TOP = '\ue01a';
    public static final Character BAMBOO_DOOR_BOTTOM = '\ue01b';
    public static final Character BAMBOO_DOOR_TOP = '\ue01c';
    public static final Character BAMBOO_FENCE = '\ue01d';
    public static final Character BAMBOO_FENCE_GATE = '\ue01e';
    public static final Character BAMBOO_FENCE_GATE_PARTICLE = '\ue01f';
    public static final Character BAMBOO_FENCE_PARTICLE = '\ue020';
    public static final Character BAMBOO_LARGE_LEAVES = '\ue021';
    public static final Character BAMBOO_MOSAIC = '\ue022';
    public static final Character BAMBOO_PLANKS = '\ue023';
    public static final Character BAMBOO_SINGLELEAF = '\ue024';
    public static final Character BAMBOO_SMALL_LEAVES = '\ue025';
    public static final Character BAMBOO_STAGE0 = '\ue026';
    public static final Character BAMBOO_STALK = '\ue027';
    public static final Character BAMBOO_TRAPDOOR = '\ue028';
    public static final Character BARREL_BOTTOM = '\ue029';
    public static final Character BARREL_SIDE = '\ue02a';
    public static final Character BARREL_TOP = '\ue02b';
    public static final Character BARREL_TOP_OPEN = '\ue02c';
    public static final Character BASALT_SIDE = '\ue02d';
    public static final Character BASALT_TOP = '\ue02e';
    public static final Character BEACON = '\ue02f';
    public static final Character BEDROCK = '\ue030';
    public static final Character BEEHIVE_END = '\ue031';
    public static final Character BEEHIVE_FRONT = '\ue032';
    public static final Character BEEHIVE_FRONT_HONEY = '\ue033';
    public static final Character BEEHIVE_SIDE = '\ue034';
    public static final Character BEETROOTS_STAGE0 = '\ue035';
    public static final Character BEETROOTS_STAGE1 = '\ue036';
    public static final Character BEETROOTS_STAGE2 = '\ue037';
    public static final Character BEETROOTS_STAGE3 = '\ue038';
    public static final Character BEE_NEST_BOTTOM = '\ue039';
    public static final Character BEE_NEST_FRONT = '\ue03a';
    public static final Character BEE_NEST_FRONT_HONEY = '\ue03b';
    public static final Character BEE_NEST_SIDE = '\ue03c';
    public static final Character BEE_NEST_TOP = '\ue03d';
    public static final Character BELL_BOTTOM = '\ue03e';
    public static final Character BELL_SIDE = '\ue03f';
    public static final Character BELL_TOP = '\ue040';
    public static final Character BIG_DRIPLEAF_SIDE = '\ue041';
    public static final Character BIG_DRIPLEAF_STEM = '\ue042';
    public static final Character BIG_DRIPLEAF_TIP = '\ue043';
    public static final Character BIG_DRIPLEAF_TOP = '\ue044';
    public static final Character BIRCH_DOOR_BOTTOM = '\ue045';
    public static final Character BIRCH_DOOR_TOP = '\ue046';
    public static final Character BIRCH_LEAVES = '\ue047';
    public static final Character BIRCH_LOG = '\ue048';
    public static final Character BIRCH_LOG_TOP = '\ue049';
    public static final Character BIRCH_PLANKS = '\ue04a';
    public static final Character BIRCH_SAPLING = '\ue04b';
    public static final Character BIRCH_TRAPDOOR = '\ue04c';
    public static final Character BLACKSTONE = '\ue04d';
    public static final Character BLACKSTONE_TOP = '\ue04e';
    public static final Character BLACK_CANDLE = '\ue04f';
    public static final Character BLACK_CANDLE_LIT = '\ue050';
    public static final Character BLACK_CONCRETE = '\ue051';
    public static final Character BLACK_CONCRETE_POWDER = '\ue052';
    public static final Character BLACK_GLAZED_TERRACOTTA = '\ue053';
    public static final Character BLACK_SHULKER_BOX = '\ue054';
    public static final Character BLACK_STAINED_GLASS = '\ue055';
    public static final Character BLACK_STAINED_GLASS_PANE_TOP = '\ue056';
    public static final Character BLACK_TERRACOTTA = '\ue057';
    public static final Character BLACK_WOOL = '\ue058';
    public static final Character BLAST_FURNACE_FRONT = '\ue059';
    public static final Character BLAST_FURNACE_FRONT_ON = '\ue05a';
    public static final Character BLAST_FURNACE_SIDE = '\ue05b';
    public static final Character BLAST_FURNACE_TOP = '\ue05c';
    public static final Character BLUE_CANDLE = '\ue05d';
    public static final Character BLUE_CANDLE_LIT = '\ue05e';
    public static final Character BLUE_CONCRETE = '\ue05f';
    public static final Character BLUE_CONCRETE_POWDER = '\ue060';
    public static final Character BLUE_GLAZED_TERRACOTTA = '\ue061';
    public static final Character BLUE_ICE = '\ue062';
    public static final Character BLUE_ORCHID = '\ue063';
    public static final Character BLUE_SHULKER_BOX = '\ue064';
    public static final Character BLUE_STAINED_GLASS = '\ue065';
    public static final Character BLUE_STAINED_GLASS_PANE_TOP = '\ue066';
    public static final Character BLUE_TERRACOTTA = '\ue067';
    public static final Character BLUE_WOOL = '\ue068';
    public static final Character BONE_BLOCK_SIDE = '\ue069';
    public static final Character BONE_BLOCK_TOP = '\ue06a';
    public static final Character BOOKSHELF = '\ue06b';
    public static final Character BRAIN_CORAL = '\ue06c';
    public static final Character BRAIN_CORAL_BLOCK = '\ue06d';
    public static final Character BRAIN_CORAL_FAN = '\ue06e';
    public static final Character BREWING_STAND = '\ue06f';
    public static final Character BREWING_STAND_BASE = '\ue070';
    public static final Character BRICKS = '\ue071';
    public static final Character BROWN_CANDLE = '\ue072';
    public static final Character BROWN_CANDLE_LIT = '\ue073';
    public static final Character BROWN_CONCRETE = '\ue074';
    public static final Character BROWN_CONCRETE_POWDER = '\ue075';
    public static final Character BROWN_GLAZED_TERRACOTTA = '\ue076';
    public static final Character BROWN_MUSHROOM = '\ue077';
    public static final Character BROWN_MUSHROOM_BLOCK = '\ue078';
    public static final Character BROWN_SHULKER_BOX = '\ue079';
    public static final Character BROWN_STAINED_GLASS = '\ue07a';
    public static final Character BROWN_STAINED_GLASS_PANE_TOP = '\ue07b';
    public static final Character BROWN_TERRACOTTA = '\ue07c';
    public static final Character BROWN_WOOL = '\ue07d';
    public static final Character BUBBLE_CORAL = '\ue07e';
    public static final Character BUBBLE_CORAL_BLOCK = '\ue07f';
    public static final Character BUBBLE_CORAL_FAN = '\ue080';
    public static final Character BUDDING_AMETHYST = '\ue081';
    public static final Character CACTUS_BOTTOM = '\ue082';
    public static final Character CACTUS_SIDE = '\ue083';
    public static final Character CACTUS_TOP = '\ue084';
    public static final Character CAKE_BOTTOM = '\ue085';
    public static final Character CAKE_INNER = '\ue086';
    public static final Character CAKE_SIDE = '\ue087';
    public static final Character CAKE_TOP = '\ue088';
    public static final Character CALCITE = '\ue089';
    public static final Character CAMPFIRE_FIRE = '\ue08a';
    public static final Character CAMPFIRE_LOG = '\ue08b';
    public static final Character CAMPFIRE_LOG_LIT = '\ue08c';
    public static final Character CANDLE = '\ue08d';
    public static final Character CANDLE_LIT = '\ue08e';
    public static final Character CARROTS_STAGE0 = '\ue08f';
    public static final Character CARROTS_STAGE1 = '\ue090';
    public static final Character CARROTS_STAGE2 = '\ue091';
    public static final Character CARROTS_STAGE3 = '\ue092';
    public static final Character CARTOGRAPHY_TABLE_SIDE1 = '\ue093';
    public static final Character CARTOGRAPHY_TABLE_SIDE2 = '\ue094';
    public static final Character CARTOGRAPHY_TABLE_SIDE3 = '\ue095';
    public static final Character CARTOGRAPHY_TABLE_TOP = '\ue096';
    public static final Character CARVED_PUMPKIN = '\ue097';
    public static final Character CAULDRON_BOTTOM = '\ue098';
    public static final Character CAULDRON_INNER = '\ue099';
    public static final Character CAULDRON_SIDE = '\ue09a';
    public static final Character CAULDRON_TOP = '\ue09b';
    public static final Character CAVE_VINES = '\ue09c';
    public static final Character CAVE_VINES_LIT = '\ue09d';
    public static final Character CAVE_VINES_PLANT = '\ue09e';
    public static final Character CAVE_VINES_PLANT_LIT = '\ue09f';
    public static final Character CHAIN = '\ue0a0';
    public static final Character CHAIN_COMMAND_BLOCK_BACK = '\ue0a1';
    public static final Character CHAIN_COMMAND_BLOCK_CONDITIONAL = '\ue0a2';
    public static final Character CHAIN_COMMAND_BLOCK_FRONT = '\ue0a3';
    public static final Character CHAIN_COMMAND_BLOCK_SIDE = '\ue0a4';
    public static final Character CHIPPED_ANVIL_TOP = '\ue0a5';
    public static final Character CHISELED_BOOKSHELF_EMPTY = '\ue0a6';
    public static final Character CHISELED_BOOKSHELF_OCCUPIED = '\ue0a7';
    public static final Character CHISELED_BOOKSHELF_SIDE = '\ue0a8';
    public static final Character CHISELED_BOOKSHELF_TOP = '\ue0a9';
    public static final Character CHISELED_DEEPSLATE = '\ue0aa';
    public static final Character CHISELED_NETHER_BRICKS = '\ue0ab';
    public static final Character CHISELED_POLISHED_BLACKSTONE = '\ue0ac';
    public static final Character CHISELED_QUARTZ_BLOCK = '\ue0ad';
    public static final Character CHISELED_QUARTZ_BLOCK_TOP = '\ue0ae';
    public static final Character CHISELED_RED_SANDSTONE = '\ue0af';
    public static final Character CHISELED_SANDSTONE = '\ue0b0';
    public static final Character CHISELED_STONE_BRICKS = '\ue0b1';
    public static final Character CHORUS_FLOWER = '\ue0b2';
    public static final Character CHORUS_FLOWER_DEAD = '\ue0b3';
    public static final Character CHORUS_PLANT = '\ue0b4';
    public static final Character CLAY = '\ue0b5';
    public static final Character COAL_BLOCK = '\ue0b6';
    public static final Character COAL_ORE = '\ue0b7';
    public static final Character COARSE_DIRT = '\ue0b8';
    public static final Character COBBLED_DEEPSLATE = '\ue0b9';
    public static final Character COBBLESTONE = '\ue0ba';
    public static final Character COBWEB = '\ue0bb';
    public static final Character COCOA_STAGE0 = '\ue0bc';
    public static final Character COCOA_STAGE1 = '\ue0bd';
    public static final Character COCOA_STAGE2 = '\ue0be';
    public static final Character COMMAND_BLOCK_BACK = '\ue0bf';
    public static final Character COMMAND_BLOCK_CONDITIONAL = '\ue0c0';
    public static final Character COMMAND_BLOCK_FRONT = '\ue0c1';
    public static final Character COMMAND_BLOCK_SIDE = '\ue0c2';
    public static final Character COMPARATOR = '\ue0c3';
    public static final Character COMPARATOR_ON = '\ue0c4';
    public static final Character COMPOSTER_BOTTOM = '\ue0c5';
    public static final Character COMPOSTER_COMPOST = '\ue0c6';
    public static final Character COMPOSTER_READY = '\ue0c7';
    public static final Character COMPOSTER_SIDE = '\ue0c8';
    public static final Character COMPOSTER_TOP = '\ue0c9';
    public static final Character CONDUIT = '\ue0ca';
    public static final Character COPPER_BLOCK = '\ue0cb';
    public static final Character COPPER_ORE = '\ue0cc';
    public static final Character CORNFLOWER = '\ue0cd';
    public static final Character CRACKED_DEEPSLATE_BRICKS = '\ue0ce';
    public static final Character CRACKED_DEEPSLATE_TILES = '\ue0cf';
    public static final Character CRACKED_NETHER_BRICKS = '\ue0d0';
    public static final Character CRACKED_POLISHED_BLACKSTONE_BRICKS = '\ue0d1';
    public static final Character CRACKED_STONE_BRICKS = '\ue0d2';
    public static final Character CRAFTING_TABLE_FRONT = '\ue0d3';
    public static final Character CRAFTING_TABLE_SIDE = '\ue0d4';
    public static final Character CRAFTING_TABLE_TOP = '\ue0d5';
    public static final Character CRIMSON_DOOR_BOTTOM = '\ue0d6';
    public static final Character CRIMSON_DOOR_TOP = '\ue0d7';
    public static final Character CRIMSON_FUNGUS = '\ue0d8';
    public static final Character CRIMSON_NYLIUM = '\ue0d9';
    public static final Character CRIMSON_NYLIUM_SIDE = '\ue0da';
    public static final Character CRIMSON_PLANKS = '\ue0db';
    public static final Character CRIMSON_ROOTS = '\ue0dc';
    public static final Character CRIMSON_ROOTS_POT = '\ue0dd';
    public static final Character CRIMSON_STEM = '\ue0de';
    public static final Character CRIMSON_STEM_TOP = '\ue0df';
    public static final Character CRIMSON_TRAPDOOR = '\ue0e0';
    public static final Character CRYING_OBSIDIAN = '\ue0e1';
    public static final Character CUT_COPPER = '\ue0e2';
    public static final Character CUT_RED_SANDSTONE = '\ue0e3';
    public static final Character CUT_SANDSTONE = '\ue0e4';
    public static final Character CYAN_CANDLE = '\ue0e5';
    public static final Character CYAN_CANDLE_LIT = '\ue0e6';
    public static final Character CYAN_CONCRETE = '\ue0e7';
    public static final Character CYAN_CONCRETE_POWDER = '\ue0e8';
    public static final Character CYAN_GLAZED_TERRACOTTA = '\ue0e9';
    public static final Character CYAN_SHULKER_BOX = '\ue0ea';
    public static final Character CYAN_STAINED_GLASS = '\ue0eb';
    public static final Character CYAN_STAINED_GLASS_PANE_TOP = '\ue0ec';
    public static final Character CYAN_TERRACOTTA = '\ue0ed';
    public static final Character CYAN_WOOL = '\ue0ee';
    public static final Character DAMAGED_ANVIL_TOP = '\ue0ef';
    public static final Character DANDELION = '\ue0f0';
    public static final Character DARK_OAK_DOOR_BOTTOM = '\ue0f1';
    public static final Character DARK_OAK_DOOR_TOP = '\ue0f2';
    public static final Character DARK_OAK_LEAVES = '\ue0f3';
    public static final Character DARK_OAK_LOG = '\ue0f4';
    public static final Character DARK_OAK_LOG_TOP = '\ue0f5';
    public static final Character DARK_OAK_PLANKS = '\ue0f6';
    public static final Character DARK_OAK_SAPLING = '\ue0f7';
    public static final Character DARK_OAK_TRAPDOOR = '\ue0f8';
    public static final Character DARK_PRISMARINE = '\ue0f9';
    public static final Character DAYLIGHT_DETECTOR_INVERTED_TOP = '\ue0fa';
    public static final Character DAYLIGHT_DETECTOR_SIDE = '\ue0fb';
    public static final Character DAYLIGHT_DETECTOR_TOP = '\ue0fc';
    public static final Character DEAD_BRAIN_CORAL = '\ue0fd';
    public static final Character DEAD_BRAIN_CORAL_BLOCK = '\ue0fe';
    public static final Character DEAD_BRAIN_CORAL_FAN = '\ue0ff';
    public static final Character DEAD_BUBBLE_CORAL = '\ue100';
    public static final Character DEAD_BUBBLE_CORAL_BLOCK = '\ue101';
    public static final Character DEAD_BUBBLE_CORAL_FAN = '\ue102';
    public static final Character DEAD_BUSH = '\ue103';
    public static final Character DEAD_FIRE_CORAL = '\ue104';
    public static final Character DEAD_FIRE_CORAL_BLOCK = '\ue105';
    public static final Character DEAD_FIRE_CORAL_FAN = '\ue106';
    public static final Character DEAD_HORN_CORAL = '\ue107';
    public static final Character DEAD_HORN_CORAL_BLOCK = '\ue108';
    public static final Character DEAD_HORN_CORAL_FAN = '\ue109';
    public static final Character DEAD_TUBE_CORAL = '\ue10a';
    public static final Character DEAD_TUBE_CORAL_BLOCK = '\ue10b';
    public static final Character DEAD_TUBE_CORAL_FAN = '\ue10c';
    public static final Character DEBUG = '\ue10d';
    public static final Character DEBUG2 = '\ue10e';
    public static final Character DEEPSLATE = '\ue10f';
    public static final Character DEEPSLATE_BRICKS = '\ue110';
    public static final Character DEEPSLATE_COAL_ORE = '\ue111';
    public static final Character DEEPSLATE_COPPER_ORE = '\ue112';
    public static final Character DEEPSLATE_DIAMOND_ORE = '\ue113';
    public static final Character DEEPSLATE_EMERALD_ORE = '\ue114';
    public static final Character DEEPSLATE_GOLD_ORE = '\ue115';
    public static final Character DEEPSLATE_IRON_ORE = '\ue116';
    public static final Character DEEPSLATE_LAPIS_ORE = '\ue117';
    public static final Character DEEPSLATE_REDSTONE_ORE = '\ue118';
    public static final Character DEEPSLATE_TILES = '\ue119';
    public static final Character DEEPSLATE_TOP = '\ue11a';
    public static final Character DESTROY_STAGE_0 = '\ue11b';
    public static final Character DESTROY_STAGE_1 = '\ue11c';
    public static final Character DESTROY_STAGE_2 = '\ue11d';
    public static final Character DESTROY_STAGE_3 = '\ue11e';
    public static final Character DESTROY_STAGE_4 = '\ue11f';
    public static final Character DESTROY_STAGE_5 = '\ue120';
    public static final Character DESTROY_STAGE_6 = '\ue121';
    public static final Character DESTROY_STAGE_7 = '\ue122';
    public static final Character DESTROY_STAGE_8 = '\ue123';
    public static final Character DESTROY_STAGE_9 = '\ue124';
    public static final Character DETECTOR_RAIL = '\ue125';
    public static final Character DETECTOR_RAIL_ON = '\ue126';
    public static final Character DIAMOND_BLOCK = '\ue127';
    public static final Character DIAMOND_ORE = '\ue128';
    public static final Character DIORITE = '\ue129';
    public static final Character DIRT = '\ue12a';
    public static final Character DIRT_PATH_SIDE = '\ue12b';
    public static final Character DIRT_PATH_TOP = '\ue12c';
    public static final Character DISPENSER_FRONT = '\ue12d';
    public static final Character DISPENSER_FRONT_VERTICAL = '\ue12e';
    public static final Character DRAGON_EGG = '\ue12f';
    public static final Character DRIED_KELP_BOTTOM = '\ue130';
    public static final Character DRIED_KELP_SIDE = '\ue131';
    public static final Character DRIED_KELP_TOP = '\ue132';
    public static final Character DRIPSTONE_BLOCK = '\ue133';
    public static final Character DROPPER_FRONT = '\ue134';
    public static final Character DROPPER_FRONT_VERTICAL = '\ue135';
    public static final Character EMERALD_BLOCK = '\ue136';
    public static final Character EMERALD_ORE = '\ue137';
    public static final Character ENCHANTING_TABLE_BOTTOM = '\ue138';
    public static final Character ENCHANTING_TABLE_SIDE = '\ue139';
    public static final Character ENCHANTING_TABLE_TOP = '\ue13a';
    public static final Character END_PORTAL_FRAME_EYE = '\ue13b';
    public static final Character END_PORTAL_FRAME_SIDE = '\ue13c';
    public static final Character END_PORTAL_FRAME_TOP = '\ue13d';
    public static final Character END_ROD = '\ue13e';
    public static final Character END_STONE = '\ue13f';
    public static final Character END_STONE_BRICKS = '\ue140';
    public static final Character EXPOSED_COPPER = '\ue141';
    public static final Character EXPOSED_CUT_COPPER = '\ue142';
    public static final Character FARMLAND = '\ue143';
    public static final Character FARMLAND_MOIST = '\ue144';
    public static final Character FERN = '\ue145';
    public static final Character FIRE_0 = '\ue146';
    public static final Character FIRE_1 = '\ue147';
    public static final Character FIRE_CORAL = '\ue148';
    public static final Character FIRE_CORAL_BLOCK = '\ue149';
    public static final Character FIRE_CORAL_FAN = '\ue14a';
    public static final Character FLETCHING_TABLE_FRONT = '\ue14b';
    public static final Character FLETCHING_TABLE_SIDE = '\ue14c';
    public static final Character FLETCHING_TABLE_TOP = '\ue14d';
    public static final Character FLOWERING_AZALEA_LEAVES = '\ue14e';
    public static final Character FLOWERING_AZALEA_SIDE = '\ue14f';
    public static final Character FLOWERING_AZALEA_TOP = '\ue150';
    public static final Character FLOWER_POT = '\ue151';
    public static final Character FROGSPAWN = '\ue152';
    public static final Character FROSTED_ICE_0 = '\ue153';
    public static final Character FROSTED_ICE_1 = '\ue154';
    public static final Character FROSTED_ICE_2 = '\ue155';
    public static final Character FROSTED_ICE_3 = '\ue156';
    public static final Character FURNACE_FRONT = '\ue157';
    public static final Character FURNACE_FRONT_ON = '\ue158';
    public static final Character FURNACE_SIDE = '\ue159';
    public static final Character FURNACE_TOP = '\ue15a';
    public static final Character GILDED_BLACKSTONE = '\ue15b';
    public static final Character GLASS = '\ue15c';
    public static final Character GLASS_PANE_TOP = '\ue15d';
    public static final Character GLOWSTONE = '\ue15e';
    public static final Character GLOW_ITEM_FRAME = '\ue15f';
    public static final Character GLOW_LICHEN = '\ue160';
    public static final Character GOLD_BLOCK = '\ue161';
    public static final Character GOLD_ORE = '\ue162';
    public static final Character GRANITE = '\ue163';
    public static final Character GRASS = '\ue164';
    public static final Character GRASS_BLOCK_SIDE = '\ue165';
    public static final Character GRASS_BLOCK_SIDE_OVERLAY = '\ue166';
    public static final Character GRASS_BLOCK_SNOW = '\ue167';
    public static final Character GRASS_BLOCK_TOP = '\ue168';
    public static final Character GRAVEL = '\ue169';
    public static final Character GRAY_CANDLE = '\ue16a';
    public static final Character GRAY_CANDLE_LIT = '\ue16b';
    public static final Character GRAY_CONCRETE = '\ue16c';
    public static final Character GRAY_CONCRETE_POWDER = '\ue16d';
    public static final Character GRAY_GLAZED_TERRACOTTA = '\ue16e';
    public static final Character GRAY_SHULKER_BOX = '\ue16f';
    public static final Character GRAY_STAINED_GLASS = '\ue170';
    public static final Character GRAY_STAINED_GLASS_PANE_TOP = '\ue171';
    public static final Character GRAY_TERRACOTTA = '\ue172';
    public static final Character GRAY_WOOL = '\ue173';
    public static final Character GREEN_CANDLE = '\ue174';
    public static final Character GREEN_CANDLE_LIT = '\ue175';
    public static final Character GREEN_CONCRETE = '\ue176';
    public static final Character GREEN_CONCRETE_POWDER = '\ue177';
    public static final Character GREEN_GLAZED_TERRACOTTA = '\ue178';
    public static final Character GREEN_SHULKER_BOX = '\ue179';
    public static final Character GREEN_STAINED_GLASS = '\ue17a';
    public static final Character GREEN_STAINED_GLASS_PANE_TOP = '\ue17b';
    public static final Character GREEN_TERRACOTTA = '\ue17c';
    public static final Character GREEN_WOOL = '\ue17d';
    public static final Character GRINDSTONE_PIVOT = '\ue17e';
    public static final Character GRINDSTONE_ROUND = '\ue17f';
    public static final Character GRINDSTONE_SIDE = '\ue180';
    public static final Character HANGING_ROOTS = '\ue181';
    public static final Character HAY_BLOCK_SIDE = '\ue182';
    public static final Character HAY_BLOCK_TOP = '\ue183';
    public static final Character HONEYCOMB_BLOCK = '\ue184';
    public static final Character HONEY_BLOCK_BOTTOM = '\ue185';
    public static final Character HONEY_BLOCK_SIDE = '\ue186';
    public static final Character HONEY_BLOCK_TOP = '\ue187';
    public static final Character HOPPER_INSIDE = '\ue188';
    public static final Character HOPPER_OUTSIDE = '\ue189';
    public static final Character HOPPER_TOP = '\ue18a';
    public static final Character HORN_CORAL = '\ue18b';
    public static final Character HORN_CORAL_BLOCK = '\ue18c';
    public static final Character HORN_CORAL_FAN = '\ue18d';
    public static final Character ICE = '\ue18e';
    public static final Character IRON_BARS = '\ue18f';
    public static final Character IRON_BLOCK = '\ue190';
    public static final Character IRON_DOOR_BOTTOM = '\ue191';
    public static final Character IRON_DOOR_TOP = '\ue192';
    public static final Character IRON_ORE = '\ue193';
    public static final Character IRON_TRAPDOOR = '\ue194';
    public static final Character ITEM_FRAME = '\ue195';
    public static final Character JACK_O_LANTERN = '\ue196';
    public static final Character JIGSAW_BOTTOM = '\ue197';
    public static final Character JIGSAW_LOCK = '\ue198';
    public static final Character JIGSAW_SIDE = '\ue199';
    public static final Character JIGSAW_TOP = '\ue19a';
    public static final Character JUKEBOX_SIDE = '\ue19b';
    public static final Character JUKEBOX_TOP = '\ue19c';
    public static final Character JUNGLE_DOOR_BOTTOM = '\ue19d';
    public static final Character JUNGLE_DOOR_TOP = '\ue19e';
    public static final Character JUNGLE_LEAVES = '\ue19f';
    public static final Character JUNGLE_LOG = '\ue1a0';
    public static final Character JUNGLE_LOG_TOP = '\ue1a1';
    public static final Character JUNGLE_PLANKS = '\ue1a2';
    public static final Character JUNGLE_SAPLING = '\ue1a3';
    public static final Character JUNGLE_TRAPDOOR = '\ue1a4';
    public static final Character KELP = '\ue1a5';
    public static final Character KELP_PLANT = '\ue1a6';
    public static final Character LADDER = '\ue1a7';
    public static final Character LANTERN = '\ue1a8';
    public static final Character LAPIS_BLOCK = '\ue1a9';
    public static final Character LAPIS_ORE = '\ue1aa';
    public static final Character LARGE_AMETHYST_BUD = '\ue1ab';
    public static final Character LARGE_FERN_BOTTOM = '\ue1ac';
    public static final Character LARGE_FERN_TOP = '\ue1ad';
    public static final Character LAVA_FLOW = '\ue1ae';
    public static final Character LAVA_STILL = '\ue1af';
    public static final Character LECTERN_BASE = '\ue1b0';
    public static final Character LECTERN_FRONT = '\ue1b1';
    public static final Character LECTERN_SIDES = '\ue1b2';
    public static final Character LECTERN_TOP = '\ue1b3';
    public static final Character LEVER = '\ue1b4';
    public static final Character LIGHTNING_ROD = '\ue1b5';
    public static final Character LIGHTNING_ROD_ON = '\ue1b6';
    public static final Character LIGHT_BLUE_CANDLE = '\ue1b7';
    public static final Character LIGHT_BLUE_CANDLE_LIT = '\ue1b8';
    public static final Character LIGHT_BLUE_CONCRETE = '\ue1b9';
    public static final Character LIGHT_BLUE_CONCRETE_POWDER = '\ue1ba';
    public static final Character LIGHT_BLUE_GLAZED_TERRACOTTA = '\ue1bb';
    public static final Character LIGHT_BLUE_SHULKER_BOX = '\ue1bc';
    public static final Character LIGHT_BLUE_STAINED_GLASS = '\ue1bd';
    public static final Character LIGHT_BLUE_STAINED_GLASS_PANE_TOP = '\ue1be';
    public static final Character LIGHT_BLUE_TERRACOTTA = '\ue1bf';
    public static final Character LIGHT_BLUE_WOOL = '\ue1c0';
    public static final Character LIGHT_GRAY_CANDLE = '\ue1c1';
    public static final Character LIGHT_GRAY_CANDLE_LIT = '\ue1c2';
    public static final Character LIGHT_GRAY_CONCRETE = '\ue1c3';
    public static final Character LIGHT_GRAY_CONCRETE_POWDER = '\ue1c4';
    public static final Character LIGHT_GRAY_GLAZED_TERRACOTTA = '\ue1c5';
    public static final Character LIGHT_GRAY_SHULKER_BOX = '\ue1c6';
    public static final Character LIGHT_GRAY_STAINED_GLASS = '\ue1c7';
    public static final Character LIGHT_GRAY_STAINED_GLASS_PANE_TOP = '\ue1c8';
    public static final Character LIGHT_GRAY_TERRACOTTA = '\ue1c9';
    public static final Character LIGHT_GRAY_WOOL = '\ue1ca';
    public static final Character LILAC_BOTTOM = '\ue1cb';
    public static final Character LILAC_TOP = '\ue1cc';
    public static final Character LILY_OF_THE_VALLEY = '\ue1cd';
    public static final Character LILY_PAD = '\ue1ce';
    public static final Character LIME_CANDLE = '\ue1cf';
    public static final Character LIME_CANDLE_LIT = '\ue1d0';
    public static final Character LIME_CONCRETE = '\ue1d1';
    public static final Character LIME_CONCRETE_POWDER = '\ue1d2';
    public static final Character LIME_GLAZED_TERRACOTTA = '\ue1d3';
    public static final Character LIME_SHULKER_BOX = '\ue1d4';
    public static final Character LIME_STAINED_GLASS = '\ue1d5';
    public static final Character LIME_STAINED_GLASS_PANE_TOP = '\ue1d6';
    public static final Character LIME_TERRACOTTA = '\ue1d7';
    public static final Character LIME_WOOL = '\ue1d8';
    public static final Character LODESTONE_SIDE = '\ue1d9';
    public static final Character LODESTONE_TOP = '\ue1da';
    public static final Character LOOM_BOTTOM = '\ue1db';
    public static final Character LOOM_FRONT = '\ue1dc';
    public static final Character LOOM_SIDE = '\ue1dd';
    public static final Character LOOM_TOP = '\ue1de';
    public static final Character MAGENTA_CANDLE = '\ue1df';
    public static final Character MAGENTA_CANDLE_LIT = '\ue1e0';
    public static final Character MAGENTA_CONCRETE = '\ue1e1';
    public static final Character MAGENTA_CONCRETE_POWDER = '\ue1e2';
    public static final Character MAGENTA_GLAZED_TERRACOTTA = '\ue1e3';
    public static final Character MAGENTA_SHULKER_BOX = '\ue1e4';
    public static final Character MAGENTA_STAINED_GLASS = '\ue1e5';
    public static final Character MAGENTA_STAINED_GLASS_PANE_TOP = '\ue1e6';
    public static final Character MAGENTA_TERRACOTTA = '\ue1e7';
    public static final Character MAGENTA_WOOL = '\ue1e8';
    public static final Character MAGMA = '\ue1e9';
    public static final Character MANGROVE_DOOR_BOTTOM = '\ue1ea';
    public static final Character MANGROVE_DOOR_TOP = '\ue1eb';
    public static final Character MANGROVE_LEAVES = '\ue1ec';
    public static final Character MANGROVE_LOG = '\ue1ed';
    public static final Character MANGROVE_LOG_TOP = '\ue1ee';
    public static final Character MANGROVE_PLANKS = '\ue1ef';
    public static final Character MANGROVE_PROPAGULE = '\ue1f0';
    public static final Character MANGROVE_PROPAGULE_HANGING = '\ue1f1';
    public static final Character MANGROVE_ROOTS_SIDE = '\ue1f2';
    public static final Character MANGROVE_ROOTS_TOP = '\ue1f3';
    public static final Character MANGROVE_TRAPDOOR = '\ue1f4';
    public static final Character MEDIUM_AMETHYST_BUD = '\ue1f5';
    public static final Character MELON_SIDE = '\ue1f6';
    public static final Character MELON_STEM = '\ue1f7';
    public static final Character MELON_TOP = '\ue1f8';
    public static final Character MOSSY_COBBLESTONE = '\ue1f9';
    public static final Character MOSSY_STONE_BRICKS = '\ue1fa';
    public static final Character MOSS_BLOCK = '\ue1fb';
    public static final Character MUD = '\ue1fc';
    public static final Character MUDDY_MANGROVE_ROOTS_SIDE = '\ue1fd';
    public static final Character MUDDY_MANGROVE_ROOTS_TOP = '\ue1fe';
    public static final Character MUD_BRICKS = '\ue1ff';
    public static final Character MUSHROOM_BLOCK_INSIDE = '\ue200';
    public static final Character MUSHROOM_STEM = '\ue201';
    public static final Character MYCELIUM_SIDE = '\ue202';
    public static final Character MYCELIUM_TOP = '\ue203';
    public static final Character NETHERITE_BLOCK = '\ue204';
    public static final Character NETHERRACK = '\ue205';
    public static final Character NETHER_BRICKS = '\ue206';
    public static final Character NETHER_GOLD_ORE = '\ue207';
    public static final Character NETHER_PORTAL = '\ue208';
    public static final Character NETHER_QUARTZ_ORE = '\ue209';
    public static final Character NETHER_SPROUTS = '\ue20a';
    public static final Character NETHER_WART_BLOCK = '\ue20b';
    public static final Character NETHER_WART_STAGE0 = '\ue20c';
    public static final Character NETHER_WART_STAGE1 = '\ue20d';
    public static final Character NETHER_WART_STAGE2 = '\ue20e';
    public static final Character NOTE_BLOCK = '\ue20f';
    public static final Character OAK_DOOR_BOTTOM = '\ue210';
    public static final Character OAK_DOOR_TOP = '\ue211';
    public static final Character OAK_LEAVES = '\ue212';
    public static final Character OAK_LOG = '\ue213';
    public static final Character OAK_LOG_TOP = '\ue214';
    public static final Character OAK_PLANKS = '\ue215';
    public static final Character OAK_SAPLING = '\ue216';
    public static final Character OAK_TRAPDOOR = '\ue217';
    public static final Character OBSERVER_BACK = '\ue218';
    public static final Character OBSERVER_BACK_ON = '\ue219';
    public static final Character OBSERVER_FRONT = '\ue21a';
    public static final Character OBSERVER_SIDE = '\ue21b';
    public static final Character OBSERVER_TOP = '\ue21c';
    public static final Character OBSIDIAN = '\ue21d';
    public static final Character OCHRE_FROGLIGHT_SIDE = '\ue21e';
    public static final Character OCHRE_FROGLIGHT_TOP = '\ue21f';
    public static final Character ORANGE_CANDLE = '\ue220';
    public static final Character ORANGE_CANDLE_LIT = '\ue221';
    public static final Character ORANGE_CONCRETE = '\ue222';
    public static final Character ORANGE_CONCRETE_POWDER = '\ue223';
    public static final Character ORANGE_GLAZED_TERRACOTTA = '\ue224';
    public static final Character ORANGE_SHULKER_BOX = '\ue225';
    public static final Character ORANGE_STAINED_GLASS = '\ue226';
    public static final Character ORANGE_STAINED_GLASS_PANE_TOP = '\ue227';
    public static final Character ORANGE_TERRACOTTA = '\ue228';
    public static final Character ORANGE_TULIP = '\ue229';
    public static final Character ORANGE_WOOL = '\ue22a';
    public static final Character OXEYE_DAISY = '\ue22b';
    public static final Character OXIDIZED_COPPER = '\ue22c';
    public static final Character OXIDIZED_CUT_COPPER = '\ue22d';
    public static final Character PACKED_ICE = '\ue22e';
    public static final Character PACKED_MUD = '\ue22f';
    public static final Character PEARLESCENT_FROGLIGHT_SIDE = '\ue230';
    public static final Character PEARLESCENT_FROGLIGHT_TOP = '\ue231';
    public static final Character PEONY_BOTTOM = '\ue232';
    public static final Character PEONY_TOP = '\ue233';
    public static final Character PINK_CANDLE = '\ue234';
    public static final Character PINK_CANDLE_LIT = '\ue235';
    public static final Character PINK_CONCRETE = '\ue236';
    public static final Character PINK_CONCRETE_POWDER = '\ue237';
    public static final Character PINK_GLAZED_TERRACOTTA = '\ue238';
    public static final Character PINK_SHULKER_BOX = '\ue239';
    public static final Character PINK_STAINED_GLASS = '\ue23a';
    public static final Character PINK_STAINED_GLASS_PANE_TOP = '\ue23b';
    public static final Character PINK_TERRACOTTA = '\ue23c';
    public static final Character PINK_TULIP = '\ue23d';
    public static final Character PINK_WOOL = '\ue23e';
    public static final Character PISTON_BOTTOM = '\ue23f';
    public static final Character PISTON_INNER = '\ue240';
    public static final Character PISTON_SIDE = '\ue241';
    public static final Character PISTON_TOP = '\ue242';
    public static final Character PISTON_TOP_STICKY = '\ue243';
    public static final Character PODZOL_SIDE = '\ue244';
    public static final Character PODZOL_TOP = '\ue245';
    public static final Character POINTED_DRIPSTONE_DOWN_BASE = '\ue246';
    public static final Character POINTED_DRIPSTONE_DOWN_FRUSTUM = '\ue247';
    public static final Character POINTED_DRIPSTONE_DOWN_MIDDLE = '\ue248';
    public static final Character POINTED_DRIPSTONE_DOWN_TIP = '\ue249';
    public static final Character POINTED_DRIPSTONE_DOWN_TIP_MERGE = '\ue24a';
    public static final Character POINTED_DRIPSTONE_UP_BASE = '\ue24b';
    public static final Character POINTED_DRIPSTONE_UP_FRUSTUM = '\ue24c';
    public static final Character POINTED_DRIPSTONE_UP_MIDDLE = '\ue24d';
    public static final Character POINTED_DRIPSTONE_UP_TIP = '\ue24e';
    public static final Character POINTED_DRIPSTONE_UP_TIP_MERGE = '\ue24f';
    public static final Character POLISHED_ANDESITE = '\ue250';
    public static final Character POLISHED_BASALT_SIDE = '\ue251';
    public static final Character POLISHED_BASALT_TOP = '\ue252';
    public static final Character POLISHED_BLACKSTONE = '\ue253';
    public static final Character POLISHED_BLACKSTONE_BRICKS = '\ue254';
    public static final Character POLISHED_DEEPSLATE = '\ue255';
    public static final Character POLISHED_DIORITE = '\ue256';
    public static final Character POLISHED_GRANITE = '\ue257';
    public static final Character POPPY = '\ue258';
    public static final Character POTATOES_STAGE0 = '\ue259';
    public static final Character POTATOES_STAGE1 = '\ue25a';
    public static final Character POTATOES_STAGE2 = '\ue25b';
    public static final Character POTATOES_STAGE3 = '\ue25c';
    public static final Character POTTED_AZALEA_BUSH_PLANT = '\ue25d';
    public static final Character POTTED_AZALEA_BUSH_SIDE = '\ue25e';
    public static final Character POTTED_AZALEA_BUSH_TOP = '\ue25f';
    public static final Character POTTED_FLOWERING_AZALEA_BUSH_PLANT = '\ue260';
    public static final Character POTTED_FLOWERING_AZALEA_BUSH_SIDE = '\ue261';
    public static final Character POTTED_FLOWERING_AZALEA_BUSH_TOP = '\ue262';
    public static final Character POWDER_SNOW = '\ue263';
    public static final Character POWERED_RAIL = '\ue264';
    public static final Character POWERED_RAIL_ON = '\ue265';
    public static final Character PRISMARINE = '\ue266';
    public static final Character PRISMARINE_BRICKS = '\ue267';
    public static final Character PUMPKIN_SIDE = '\ue268';
    public static final Character PUMPKIN_STEM = '\ue269';
    public static final Character PUMPKIN_TOP = '\ue26a';
    public static final Character PURPLE_CANDLE = '\ue26b';
    public static final Character PURPLE_CANDLE_LIT = '\ue26c';
    public static final Character PURPLE_CONCRETE = '\ue26d';
    public static final Character PURPLE_CONCRETE_POWDER = '\ue26e';
    public static final Character PURPLE_GLAZED_TERRACOTTA = '\ue26f';
    public static final Character PURPLE_SHULKER_BOX = '\ue270';
    public static final Character PURPLE_STAINED_GLASS = '\ue271';
    public static final Character PURPLE_STAINED_GLASS_PANE_TOP = '\ue272';
    public static final Character PURPLE_TERRACOTTA = '\ue273';
    public static final Character PURPLE_WOOL = '\ue274';
    public static final Character PURPUR_BLOCK = '\ue275';
    public static final Character PURPUR_PILLAR = '\ue276';
    public static final Character PURPUR_PILLAR_TOP = '\ue277';
    public static final Character QUARTZ_BLOCK_BOTTOM = '\ue278';
    public static final Character QUARTZ_BLOCK_SIDE = '\ue279';
    public static final Character QUARTZ_BLOCK_TOP = '\ue27a';
    public static final Character QUARTZ_BRICKS = '\ue27b';
    public static final Character QUARTZ_PILLAR = '\ue27c';
    public static final Character QUARTZ_PILLAR_TOP = '\ue27d';
    public static final Character RAIL = '\ue27e';
    public static final Character RAIL_CORNER = '\ue27f';
    public static final Character RAW_COPPER_BLOCK = '\ue280';
    public static final Character RAW_GOLD_BLOCK = '\ue281';
    public static final Character RAW_IRON_BLOCK = '\ue282';
    public static final Character REDSTONE_BLOCK = '\ue283';
    public static final Character REDSTONE_DUST_DOT = '\ue284';
    public static final Character REDSTONE_DUST_LINE0 = '\ue285';
    public static final Character REDSTONE_DUST_LINE1 = '\ue286';
    public static final Character REDSTONE_DUST_OVERLAY = '\ue287';
    public static final Character REDSTONE_LAMP = '\ue288';
    public static final Character REDSTONE_LAMP_ON = '\ue289';
    public static final Character REDSTONE_ORE = '\ue28a';
    public static final Character REDSTONE_TORCH = '\ue28b';
    public static final Character REDSTONE_TORCH_OFF = '\ue28c';
    public static final Character RED_CANDLE = '\ue28d';
    public static final Character RED_CANDLE_LIT = '\ue28e';
    public static final Character RED_CONCRETE = '\ue28f';
    public static final Character RED_CONCRETE_POWDER = '\ue290';
    public static final Character RED_GLAZED_TERRACOTTA = '\ue291';
    public static final Character RED_MUSHROOM = '\ue292';
    public static final Character RED_MUSHROOM_BLOCK = '\ue293';
    public static final Character RED_NETHER_BRICKS = '\ue294';
    public static final Character RED_SAND = '\ue295';
    public static final Character RED_SANDSTONE = '\ue296';
    public static final Character RED_SANDSTONE_BOTTOM = '\ue297';
    public static final Character RED_SANDSTONE_TOP = '\ue298';
    public static final Character RED_SHULKER_BOX = '\ue299';
    public static final Character RED_STAINED_GLASS = '\ue29a';
    public static final Character RED_STAINED_GLASS_PANE_TOP = '\ue29b';
    public static final Character RED_TERRACOTTA = '\ue29c';
    public static final Character RED_TULIP = '\ue29d';
    public static final Character RED_WOOL = '\ue29e';
    public static final Character REINFORCED_DEEPSLATE_BOTTOM = '\ue29f';
    public static final Character REINFORCED_DEEPSLATE_SIDE = '\ue2a0';
    public static final Character REINFORCED_DEEPSLATE_TOP = '\ue2a1';
    public static final Character REPEATER = '\ue2a2';
    public static final Character REPEATER_ON = '\ue2a3';
    public static final Character REPEATING_COMMAND_BLOCK_BACK = '\ue2a4';
    public static final Character REPEATING_COMMAND_BLOCK_CONDITIONAL = '\ue2a5';
    public static final Character REPEATING_COMMAND_BLOCK_FRONT = '\ue2a6';
    public static final Character REPEATING_COMMAND_BLOCK_SIDE = '\ue2a7';
    public static final Character RESPAWN_ANCHOR_BOTTOM = '\ue2a8';
    public static final Character RESPAWN_ANCHOR_SIDE0 = '\ue2a9';
    public static final Character RESPAWN_ANCHOR_SIDE1 = '\ue2aa';
    public static final Character RESPAWN_ANCHOR_SIDE2 = '\ue2ab';
    public static final Character RESPAWN_ANCHOR_SIDE3 = '\ue2ac';
    public static final Character RESPAWN_ANCHOR_SIDE4 = '\ue2ad';
    public static final Character RESPAWN_ANCHOR_TOP = '\ue2ae';
    public static final Character RESPAWN_ANCHOR_TOP_OFF = '\ue2af';
    public static final Character ROOTED_DIRT = '\ue2b0';
    public static final Character ROSE_BUSH_BOTTOM = '\ue2b1';
    public static final Character ROSE_BUSH_TOP = '\ue2b2';
    public static final Character SAND = '\ue2b3';
    public static final Character SANDSTONE = '\ue2b4';
    public static final Character SANDSTONE_BOTTOM = '\ue2b5';
    public static final Character SANDSTONE_TOP = '\ue2b6';
    public static final Character SCAFFOLDING_BOTTOM = '\ue2b7';
    public static final Character SCAFFOLDING_SIDE = '\ue2b8';
    public static final Character SCAFFOLDING_TOP = '\ue2b9';
    public static final Character SCULK = '\ue2ba';
    public static final Character SCULK_CATALYST_BOTTOM = '\ue2bb';
    public static final Character SCULK_CATALYST_SIDE = '\ue2bc';
    public static final Character SCULK_CATALYST_SIDE_BLOOM = '\ue2bd';
    public static final Character SCULK_CATALYST_TOP = '\ue2be';
    public static final Character SCULK_CATALYST_TOP_BLOOM = '\ue2bf';
    public static final Character SCULK_SENSOR_BOTTOM = '\ue2c0';
    public static final Character SCULK_SENSOR_SIDE = '\ue2c1';
    public static final Character SCULK_SENSOR_TENDRIL_ACTIVE = '\ue2c2';
    public static final Character SCULK_SENSOR_TENDRIL_INACTIVE = '\ue2c3';
    public static final Character SCULK_SENSOR_TOP = '\ue2c4';
    public static final Character SCULK_SHRIEKER_BOTTOM = '\ue2c5';
    public static final Character SCULK_SHRIEKER_CAN_SUMMON_INNER_TOP = '\ue2c6';
    public static final Character SCULK_SHRIEKER_INNER_TOP = '\ue2c7';
    public static final Character SCULK_SHRIEKER_SIDE = '\ue2c8';
    public static final Character SCULK_SHRIEKER_TOP = '\ue2c9';
    public static final Character SCULK_VEIN = '\ue2ca';
    public static final Character SEAGRASS = '\ue2cb';
    public static final Character SEA_LANTERN = '\ue2cc';
    public static final Character SEA_PICKLE = '\ue2cd';
    public static final Character SHROOMLIGHT = '\ue2ce';
    public static final Character SHULKER_BOX = '\ue2cf';
    public static final Character SLIME_BLOCK = '\ue2d0';
    public static final Character SMALL_AMETHYST_BUD = '\ue2d1';
    public static final Character SMALL_DRIPLEAF_SIDE = '\ue2d2';
    public static final Character SMALL_DRIPLEAF_STEM_BOTTOM = '\ue2d3';
    public static final Character SMALL_DRIPLEAF_STEM_TOP = '\ue2d4';
    public static final Character SMALL_DRIPLEAF_TOP = '\ue2d5';
    public static final Character SMITHING_TABLE_BOTTOM = '\ue2d6';
    public static final Character SMITHING_TABLE_FRONT = '\ue2d7';
    public static final Character SMITHING_TABLE_SIDE = '\ue2d8';
    public static final Character SMITHING_TABLE_TOP = '\ue2d9';
    public static final Character SMOKER_BOTTOM = '\ue2da';
    public static final Character SMOKER_FRONT = '\ue2db';
    public static final Character SMOKER_FRONT_ON = '\ue2dc';
    public static final Character SMOKER_SIDE = '\ue2dd';
    public static final Character SMOKER_TOP = '\ue2de';
    public static final Character SMOOTH_BASALT = '\ue2df';
    public static final Character SMOOTH_STONE = '\ue2e0';
    public static final Character SMOOTH_STONE_SLAB_SIDE = '\ue2e1';
    public static final Character SNOW = '\ue2e2';
    public static final Character SOUL_CAMPFIRE_FIRE = '\ue2e3';
    public static final Character SOUL_CAMPFIRE_LOG_LIT = '\ue2e4';
    public static final Character SOUL_FIRE_0 = '\ue2e5';
    public static final Character SOUL_FIRE_1 = '\ue2e6';
    public static final Character SOUL_LANTERN = '\ue2e7';
    public static final Character SOUL_SAND = '\ue2e8';
    public static final Character SOUL_SOIL = '\ue2e9';
    public static final Character SOUL_TORCH = '\ue2ea';
    public static final Character SPAWNER = '\ue2eb';
    public static final Character SPONGE = '\ue2ec';
    public static final Character SPORE_BLOSSOM = '\ue2ed';
    public static final Character SPORE_BLOSSOM_BASE = '\ue2ee';
    public static final Character SPRUCE_DOOR_BOTTOM = '\ue2ef';
    public static final Character SPRUCE_DOOR_TOP = '\ue2f0';
    public static final Character SPRUCE_LEAVES = '\ue2f1';
    public static final Character SPRUCE_LOG = '\ue2f2';
    public static final Character SPRUCE_LOG_TOP = '\ue2f3';
    public static final Character SPRUCE_PLANKS = '\ue2f4';
    public static final Character SPRUCE_SAPLING = '\ue2f5';
    public static final Character SPRUCE_TRAPDOOR = '\ue2f6';
    public static final Character STONE = '\ue2f7';
    public static final Character STONECUTTER_BOTTOM = '\ue2f8';
    public static final Character STONECUTTER_SAW = '\ue2f9';
    public static final Character STONECUTTER_SIDE = '\ue2fa';
    public static final Character STONECUTTER_TOP = '\ue2fb';
    public static final Character STONE_BRICKS = '\ue2fc';
    public static final Character STRIPPED_ACACIA_LOG = '\ue2fd';
    public static final Character STRIPPED_ACACIA_LOG_TOP = '\ue2fe';
    public static final Character STRIPPED_BAMBOO_BLOCK = '\ue2ff';
    public static final Character STRIPPED_BAMBOO_BLOCK_TOP = '\ue300';
    public static final Character STRIPPED_BIRCH_LOG = '\ue301';
    public static final Character STRIPPED_BIRCH_LOG_TOP = '\ue302';
    public static final Character STRIPPED_CRIMSON_STEM = '\ue303';
    public static final Character STRIPPED_CRIMSON_STEM_TOP = '\ue304';
    public static final Character STRIPPED_DARK_OAK_LOG = '\ue305';
    public static final Character STRIPPED_DARK_OAK_LOG_TOP = '\ue306';
    public static final Character STRIPPED_JUNGLE_LOG = '\ue307';
    public static final Character STRIPPED_JUNGLE_LOG_TOP = '\ue308';
    public static final Character STRIPPED_MANGROVE_LOG = '\ue309';
    public static final Character STRIPPED_MANGROVE_LOG_TOP = '\ue30a';
    public static final Character STRIPPED_OAK_LOG = '\ue30b';
    public static final Character STRIPPED_OAK_LOG_TOP = '\ue30c';
    public static final Character STRIPPED_SPRUCE_LOG = '\ue30d';
    public static final Character STRIPPED_SPRUCE_LOG_TOP = '\ue30e';
    public static final Character STRIPPED_WARPED_STEM = '\ue30f';
    public static final Character STRIPPED_WARPED_STEM_TOP = '\ue310';
    public static final Character STRUCTURE_BLOCK = '\ue311';
    public static final Character STRUCTURE_BLOCK_CORNER = '\ue312';
    public static final Character STRUCTURE_BLOCK_DATA = '\ue313';
    public static final Character STRUCTURE_BLOCK_LOAD = '\ue314';
    public static final Character STRUCTURE_BLOCK_SAVE = '\ue315';
    public static final Character SUGAR_CANE = '\ue316';
    public static final Character SUNFLOWER_BACK = '\ue317';
    public static final Character SUNFLOWER_BOTTOM = '\ue318';
    public static final Character SUNFLOWER_FRONT = '\ue319';
    public static final Character SUNFLOWER_TOP = '\ue31a';
    public static final Character SWEET_BERRY_BUSH_STAGE0 = '\ue31b';
    public static final Character SWEET_BERRY_BUSH_STAGE1 = '\ue31c';
    public static final Character SWEET_BERRY_BUSH_STAGE2 = '\ue31d';
    public static final Character SWEET_BERRY_BUSH_STAGE3 = '\ue31e';
    public static final Character TALL_GRASS_BOTTOM = '\ue31f';
    public static final Character TALL_GRASS_TOP = '\ue320';
    public static final Character TALL_SEAGRASS_BOTTOM = '\ue321';
    public static final Character TALL_SEAGRASS_TOP = '\ue322';
    public static final Character TARGET_SIDE = '\ue323';
    public static final Character TARGET_TOP = '\ue324';
    public static final Character TERRACOTTA = '\ue325';
    public static final Character TINTED_GLASS = '\ue326';
    public static final Character TNT_BOTTOM = '\ue327';
    public static final Character TNT_SIDE = '\ue328';
    public static final Character TNT_TOP = '\ue329';
    public static final Character TORCH = '\ue32a';
    public static final Character TRIPWIRE = '\ue32b';
    public static final Character TRIPWIRE_HOOK = '\ue32c';
    public static final Character TUBE_CORAL = '\ue32d';
    public static final Character TUBE_CORAL_BLOCK = '\ue32e';
    public static final Character TUBE_CORAL_FAN = '\ue32f';
    public static final Character TUFF = '\ue330';
    public static final Character TURTLE_EGG = '\ue331';
    public static final Character TURTLE_EGG_SLIGHTLY_CRACKED = '\ue332';
    public static final Character TURTLE_EGG_VERY_CRACKED = '\ue333';
    public static final Character TWISTING_VINES = '\ue334';
    public static final Character TWISTING_VINES_PLANT = '\ue335';
    public static final Character VERDANT_FROGLIGHT_SIDE = '\ue336';
    public static final Character VERDANT_FROGLIGHT_TOP = '\ue337';
    public static final Character VINE = '\ue338';
    public static final Character WARPED_DOOR_BOTTOM = '\ue339';
    public static final Character WARPED_DOOR_TOP = '\ue33a';
    public static final Character WARPED_FUNGUS = '\ue33b';
    public static final Character WARPED_NYLIUM = '\ue33c';
    public static final Character WARPED_NYLIUM_SIDE = '\ue33d';
    public static final Character WARPED_PLANKS = '\ue33e';
    public static final Character WARPED_ROOTS = '\ue33f';
    public static final Character WARPED_ROOTS_POT = '\ue340';
    public static final Character WARPED_STEM = '\ue341';
    public static final Character WARPED_STEM_TOP = '\ue342';
    public static final Character WARPED_TRAPDOOR = '\ue343';
    public static final Character WARPED_WART_BLOCK = '\ue344';
    public static final Character WATER_FLOW = '\ue345';
    public static final Character WATER_OVERLAY = '\ue346';
    public static final Character WATER_STILL = '\ue347';
    public static final Character WEATHERED_COPPER = '\ue348';
    public static final Character WEATHERED_CUT_COPPER = '\ue349';
    public static final Character WEEPING_VINES = '\ue34a';
    public static final Character WEEPING_VINES_PLANT = '\ue34b';
    public static final Character WET_SPONGE = '\ue34c';
    public static final Character WHEAT_STAGE0 = '\ue34d';
    public static final Character WHEAT_STAGE1 = '\ue34e';
    public static final Character WHEAT_STAGE2 = '\ue34f';
    public static final Character WHEAT_STAGE3 = '\ue350';
    public static final Character WHEAT_STAGE4 = '\ue351';
    public static final Character WHEAT_STAGE5 = '\ue352';
    public static final Character WHEAT_STAGE6 = '\ue353';
    public static final Character WHEAT_STAGE7 = '\ue354';
    public static final Character WHITE_CANDLE = '\ue355';
    public static final Character WHITE_CANDLE_LIT = '\ue356';
    public static final Character WHITE_CONCRETE = '\ue357';
    public static final Character WHITE_CONCRETE_POWDER = '\ue358';
    public static final Character WHITE_GLAZED_TERRACOTTA = '\ue359';
    public static final Character WHITE_SHULKER_BOX = '\ue35a';
    public static final Character WHITE_STAINED_GLASS = '\ue35b';
    public static final Character WHITE_STAINED_GLASS_PANE_TOP = '\ue35c';
    public static final Character WHITE_TERRACOTTA = '\ue35d';
    public static final Character WHITE_TULIP = '\ue35e';
    public static final Character WHITE_WOOL = '\ue35f';
    public static final Character WITHER_ROSE = '\ue360';
    public static final Character YELLOW_CANDLE = '\ue361';
    public static final Character YELLOW_CANDLE_LIT = '\ue362';
    public static final Character YELLOW_CONCRETE = '\ue363';
    public static final Character YELLOW_CONCRETE_POWDER = '\ue364';
    public static final Character YELLOW_GLAZED_TERRACOTTA = '\ue365';
    public static final Character YELLOW_SHULKER_BOX = '\ue366';
    public static final Character YELLOW_STAINED_GLASS = '\ue367';
    public static final Character YELLOW_STAINED_GLASS_PANE_TOP = '\ue368';
    public static final Character YELLOW_TERRACOTTA = '\ue369';
    public static final Character YELLOW_WOOL = '\ue36a';
    public static final Character CALIBRATED_SCULK_SENSOR_AMETHYST = '\ue572';
    public static final Character CALIBRATED_SCULK_SENSOR_INPUT_SIDE = '\ue573';
    public static final Character CALIBRATED_SCULK_SENSOR_TOP = '\ue574';
    public static final Character CHERRY_DOOR_BOTTOM = '\ue575';
    public static final Character CHERRY_DOOR_TOP = '\ue576';
    public static final Character CHERRY_LEAVES = '\ue577';
    public static final Character CHERRY_LOG = '\ue578';
    public static final Character CHERRY_LOG_TOP = '\ue579';
    public static final Character CHERRY_PLANKS = '\ue57a';
    public static final Character CHERRY_SAPLING = '\ue57b';
    public static final Character CHERRY_TRAPDOOR = '\ue57c';
    public static final Character CHISELED_COPPER = '\ue57d';
    public static final Character CHISELED_TUFF = '\ue57e';
    public static final Character CHISELED_TUFF_BRICKS = '\ue57f';
    public static final Character CHISELED_TUFF_BRICKS_TOP = '\ue580';
    public static final Character CHISELED_TUFF_TOP = '\ue581';
    public static final Character COPPER_BULB = '\ue582';
    public static final Character COPPER_BULB_LIT = '\ue583';
    public static final Character COPPER_BULB_LIT_POWERED = '\ue584';
    public static final Character COPPER_BULB_POWERED = '\ue585';
    public static final Character COPPER_DOOR_BOTTOM = '\ue586';
    public static final Character COPPER_DOOR_TOP = '\ue587';
    public static final Character COPPER_GRATE = '\ue588';
    public static final Character COPPER_TRAPDOOR = '\ue589';
    public static final Character CRAFTER_BOTTOM = '\ue58a';
    public static final Character CRAFTER_EAST = '\ue58b';
    public static final Character CRAFTER_EAST_CRAFTING = '\ue58c';
    public static final Character CRAFTER_EAST_TRIGGERED = '\ue58d';
    public static final Character CRAFTER_NORTH = '\ue58e';
    public static final Character CRAFTER_NORTH_CRAFTING = '\ue58f';
    public static final Character CRAFTER_SOUTH = '\ue590';
    public static final Character CRAFTER_SOUTH_TRIGGERED = '\ue591';
    public static final Character CRAFTER_TOP = '\ue592';
    public static final Character CRAFTER_TOP_CRAFTING = '\ue593';
    public static final Character CRAFTER_TOP_TRIGGERED = '\ue594';
    public static final Character CRAFTER_WEST = '\ue595';
    public static final Character CRAFTER_WEST_CRAFTING = '\ue596';
    public static final Character CRAFTER_WEST_TRIGGERED = '\ue597';
    public static final Character EXPOSED_CHISELED_COPPER = '\ue598';
    public static final Character EXPOSED_COPPER_BULB = '\ue599';
    public static final Character EXPOSED_COPPER_BULB_LIT = '\ue59a';
    public static final Character EXPOSED_COPPER_BULB_LIT_POWERED = '\ue59b';
    public static final Character EXPOSED_COPPER_BULB_POWERED = '\ue59c';
    public static final Character EXPOSED_COPPER_DOOR_BOTTOM = '\ue59d';
    public static final Character EXPOSED_COPPER_DOOR_TOP = '\ue59e';
    public static final Character EXPOSED_COPPER_GRATE = '\ue59f';
    public static final Character EXPOSED_COPPER_TRAPDOOR = '\ue5a0';
    public static final Character HEAVY_CORE = '\ue5a1';
    public static final Character OXIDIZED_CHISELED_COPPER = '\ue5a2';
    public static final Character OXIDIZED_COPPER_BULB = '\ue5a3';
    public static final Character OXIDIZED_COPPER_BULB_LIT = '\ue5a4';
    public static final Character OXIDIZED_COPPER_BULB_LIT_POWERED = '\ue5a5';
    public static final Character OXIDIZED_COPPER_BULB_POWERED = '\ue5a6';
    public static final Character OXIDIZED_COPPER_DOOR_BOTTOM = '\ue5a7';
    public static final Character OXIDIZED_COPPER_DOOR_TOP = '\ue5a8';
    public static final Character OXIDIZED_COPPER_GRATE = '\ue5a9';
    public static final Character OXIDIZED_COPPER_TRAPDOOR = '\ue5aa';
    public static final Character PINK_PETALS = '\ue5ab';
    public static final Character PINK_PETALS_STEM = '\ue5ac';
    public static final Character PITCHER_CROP_BOTTOM = '\ue5ad';
    public static final Character PITCHER_CROP_BOTTOM_STAGE_1 = '\ue5ae';
    public static final Character PITCHER_CROP_BOTTOM_STAGE_2 = '\ue5af';
    public static final Character PITCHER_CROP_BOTTOM_STAGE_3 = '\ue5b0';
    public static final Character PITCHER_CROP_BOTTOM_STAGE_4 = '\ue5b1';
    public static final Character PITCHER_CROP_SIDE = '\ue5b2';
    public static final Character PITCHER_CROP_TOP = '\ue5b3';
    public static final Character PITCHER_CROP_TOP_STAGE_3 = '\ue5b4';
    public static final Character PITCHER_CROP_TOP_STAGE_4 = '\ue5b5';
    public static final Character POLISHED_TUFF = '\ue5b6';
    public static final Character SHORT_GRASS = '\ue5b7';
    public static final Character SNIFFER_EGG_NOT_CRACKED_BOTTOM = '\ue5b8';
    public static final Character SNIFFER_EGG_NOT_CRACKED_EAST = '\ue5b9';
    public static final Character SNIFFER_EGG_NOT_CRACKED_NORTH = '\ue5ba';
    public static final Character SNIFFER_EGG_NOT_CRACKED_SOUTH = '\ue5bb';
    public static final Character SNIFFER_EGG_NOT_CRACKED_TOP = '\ue5bc';
    public static final Character SNIFFER_EGG_NOT_CRACKED_WEST = '\ue5bd';
    public static final Character SNIFFER_EGG_SLIGHTLY_CRACKED_BOTTOM = '\ue5be';
    public static final Character SNIFFER_EGG_SLIGHTLY_CRACKED_EAST = '\ue5bf';
    public static final Character SNIFFER_EGG_SLIGHTLY_CRACKED_NORTH = '\ue5c0';
    public static final Character SNIFFER_EGG_SLIGHTLY_CRACKED_SOUTH = '\ue5c1';
    public static final Character SNIFFER_EGG_SLIGHTLY_CRACKED_TOP = '\ue5c2';
    public static final Character SNIFFER_EGG_SLIGHTLY_CRACKED_WEST = '\ue5c3';
    public static final Character SNIFFER_EGG_VERY_CRACKED_BOTTOM = '\ue5c4';
    public static final Character SNIFFER_EGG_VERY_CRACKED_EAST = '\ue5c5';
    public static final Character SNIFFER_EGG_VERY_CRACKED_NORTH = '\ue5c6';
    public static final Character SNIFFER_EGG_VERY_CRACKED_SOUTH = '\ue5c7';
    public static final Character SNIFFER_EGG_VERY_CRACKED_TOP = '\ue5c8';
    public static final Character SNIFFER_EGG_VERY_CRACKED_WEST = '\ue5c9';
    public static final Character STRIPPED_CHERRY_LOG = '\ue5ca';
    public static final Character STRIPPED_CHERRY_LOG_TOP = '\ue5cb';
    public static final Character SUSPICIOUS_GRAVEL_0 = '\ue5cc';
    public static final Character SUSPICIOUS_GRAVEL_1 = '\ue5cd';
    public static final Character SUSPICIOUS_GRAVEL_2 = '\ue5ce';
    public static final Character SUSPICIOUS_GRAVEL_3 = '\ue5cf';
    public static final Character SUSPICIOUS_SAND_0 = '\ue5d0';
    public static final Character SUSPICIOUS_SAND_1 = '\ue5d1';
    public static final Character SUSPICIOUS_SAND_2 = '\ue5d2';
    public static final Character SUSPICIOUS_SAND_3 = '\ue5d3';
    public static final Character TORCHFLOWER = '\ue5d4';
    public static final Character TORCHFLOWER_CROP_STAGE0 = '\ue5d5';
    public static final Character TORCHFLOWER_CROP_STAGE1 = '\ue5d6';
    public static final Character TRIAL_SPAWNER_BOTTOM = '\ue5d7';
    public static final Character TRIAL_SPAWNER_SIDE_ACTIVE = '\ue5d8';
    public static final Character TRIAL_SPAWNER_SIDE_ACTIVE_OMINOUS = '\ue5d9';
    public static final Character TRIAL_SPAWNER_SIDE_INACTIVE = '\ue5da';
    public static final Character TRIAL_SPAWNER_SIDE_INACTIVE_OMINOUS = '\ue5db';
    public static final Character TRIAL_SPAWNER_TOP_ACTIVE = '\ue5dc';
    public static final Character TRIAL_SPAWNER_TOP_ACTIVE_OMINOUS = '\ue5dd';
    public static final Character TRIAL_SPAWNER_TOP_EJECTING_REWARD = '\ue5de';
    public static final Character TRIAL_SPAWNER_TOP_EJECTING_REWARD_OMINOUS = '\ue5df';
    public static final Character TRIAL_SPAWNER_TOP_INACTIVE = '\ue5e0';
    public static final Character TRIAL_SPAWNER_TOP_INACTIVE_OMINOUS = '\ue5e1';
    public static final Character TUFF_BRICKS = '\ue5e2';
    public static final Character VAULT_BOTTOM = '\ue5e3';
    public static final Character VAULT_BOTTOM_OMINOUS = '\ue5e4';
    public static final Character VAULT_FRONT_EJECTING = '\ue5e5';
    public static final Character VAULT_FRONT_EJECTING_OMINOUS = '\ue5e6';
    public static final Character VAULT_FRONT_OFF = '\ue5e7';
    public static final Character VAULT_FRONT_OFF_OMINOUS = '\ue5e8';
    public static final Character VAULT_FRONT_ON = '\ue5e9';
    public static final Character VAULT_FRONT_ON_OMINOUS = '\ue5ea';
    public static final Character VAULT_SIDE_OFF = '\ue5eb';
    public static final Character VAULT_SIDE_OFF_OMINOUS = '\ue5ec';
    public static final Character VAULT_SIDE_ON = '\ue5ed';
    public static final Character VAULT_SIDE_ON_OMINOUS = '\ue5ee';
    public static final Character VAULT_TOP = '\ue5ef';
    public static final Character VAULT_TOP_EJECTING = '\ue5f0';
    public static final Character VAULT_TOP_EJECTING_OMINOUS = '\ue5f1';
    public static final Character VAULT_TOP_OMINOUS = '\ue5f2';
    public static final Character WEATHERED_CHISELED_COPPER = '\ue5f3';
    public static final Character WEATHERED_COPPER_BULB = '\ue5f4';
    public static final Character WEATHERED_COPPER_BULB_LIT = '\ue5f5';
    public static final Character WEATHERED_COPPER_BULB_LIT_POWERED = '\ue5f6';
    public static final Character WEATHERED_COPPER_BULB_POWERED = '\ue5f7';
    public static final Character WEATHERED_COPPER_DOOR_BOTTOM = '\ue5f8';
    public static final Character WEATHERED_COPPER_DOOR_TOP = '\ue5f9';
    public static final Character WEATHERED_COPPER_GRATE = '\ue5fa';
    public static final Character WEATHERED_COPPER_TRAPDOOR = '\ue5fb';

    public static @Nullable Character fromMaterial(Material material) {
        if (material == Material.ACACIA_LEAVES) return ACACIA_LEAVES;
        if (material == Material.ACACIA_LOG) return ACACIA_LOG;
        if (material == Material.ACACIA_PLANKS) return ACACIA_PLANKS;
        if (material == Material.ACACIA_SAPLING) return ACACIA_SAPLING;
        if (material == Material.ACACIA_TRAPDOOR) return ACACIA_TRAPDOOR;
        if (material == Material.ACTIVATOR_RAIL) return ACTIVATOR_RAIL;
        if (material == Material.ALLIUM) return ALLIUM;
        if (material == Material.AMETHYST_BLOCK) return AMETHYST_BLOCK;
        if (material == Material.AMETHYST_CLUSTER) return AMETHYST_CLUSTER;
        if (material == Material.ANDESITE) return ANDESITE;
        if (material == Material.ANVIL) return ANVIL;
        if (material == Material.ATTACHED_MELON_STEM) return ATTACHED_MELON_STEM;
        if (material == Material.ATTACHED_PUMPKIN_STEM) return ATTACHED_PUMPKIN_STEM;
        if (material == Material.AZALEA_LEAVES) return AZALEA_LEAVES;
        if (material == Material.AZURE_BLUET) return AZURE_BLUET;
        if (material == Material.BAMBOO_BLOCK) return BAMBOO_BLOCK;
        if (material == Material.BAMBOO_FENCE) return BAMBOO_FENCE;
        if (material == Material.BAMBOO_FENCE_GATE) return BAMBOO_FENCE_GATE;
        if (material == Material.BAMBOO_MOSAIC) return BAMBOO_MOSAIC;
        if (material == Material.BAMBOO_PLANKS) return BAMBOO_PLANKS;
        if (material == Material.BAMBOO_TRAPDOOR) return BAMBOO_TRAPDOOR;
        if (material == Material.BEACON) return BEACON;
        if (material == Material.BEDROCK) return BEDROCK;
        if (material == Material.BIG_DRIPLEAF_STEM) return BIG_DRIPLEAF_STEM;
        if (material == Material.BIRCH_LEAVES) return BIRCH_LEAVES;
        if (material == Material.BIRCH_LOG) return BIRCH_LOG;
        if (material == Material.BIRCH_PLANKS) return BIRCH_PLANKS;
        if (material == Material.BIRCH_SAPLING) return BIRCH_SAPLING;
        if (material == Material.BIRCH_TRAPDOOR) return BIRCH_TRAPDOOR;
        if (material == Material.BLACKSTONE) return BLACKSTONE;
        if (material == Material.BLACK_CANDLE) return BLACK_CANDLE;
        if (material == Material.BLACK_CONCRETE) return BLACK_CONCRETE;
        if (material == Material.BLACK_CONCRETE_POWDER) return BLACK_CONCRETE_POWDER;
        if (material == Material.BLACK_GLAZED_TERRACOTTA) return BLACK_GLAZED_TERRACOTTA;
        if (material == Material.BLACK_SHULKER_BOX) return BLACK_SHULKER_BOX;
        if (material == Material.BLACK_STAINED_GLASS) return BLACK_STAINED_GLASS;
        if (material == Material.BLACK_TERRACOTTA) return BLACK_TERRACOTTA;
        if (material == Material.BLACK_WOOL) return BLACK_WOOL;
        if (material == Material.BLUE_CANDLE) return BLUE_CANDLE;
        if (material == Material.BLUE_CONCRETE) return BLUE_CONCRETE;
        if (material == Material.BLUE_CONCRETE_POWDER) return BLUE_CONCRETE_POWDER;
        if (material == Material.BLUE_GLAZED_TERRACOTTA) return BLUE_GLAZED_TERRACOTTA;
        if (material == Material.BLUE_ICE) return BLUE_ICE;
        if (material == Material.BLUE_ORCHID) return BLUE_ORCHID;
        if (material == Material.BLUE_SHULKER_BOX) return BLUE_SHULKER_BOX;
        if (material == Material.BLUE_STAINED_GLASS) return BLUE_STAINED_GLASS;
        if (material == Material.BLUE_TERRACOTTA) return BLUE_TERRACOTTA;
        if (material == Material.BLUE_WOOL) return BLUE_WOOL;
        if (material == Material.BOOKSHELF) return BOOKSHELF;
        if (material == Material.BRAIN_CORAL) return BRAIN_CORAL;
        if (material == Material.BRAIN_CORAL_BLOCK) return BRAIN_CORAL_BLOCK;
        if (material == Material.BRAIN_CORAL_FAN) return BRAIN_CORAL_FAN;
        if (material == Material.BREWING_STAND) return BREWING_STAND;
        if (material == Material.BRICKS) return BRICKS;
        if (material == Material.BROWN_CANDLE) return BROWN_CANDLE;
        if (material == Material.BROWN_CONCRETE) return BROWN_CONCRETE;
        if (material == Material.BROWN_CONCRETE_POWDER) return BROWN_CONCRETE_POWDER;
        if (material == Material.BROWN_GLAZED_TERRACOTTA) return BROWN_GLAZED_TERRACOTTA;
        if (material == Material.BROWN_MUSHROOM) return BROWN_MUSHROOM;
        if (material == Material.BROWN_MUSHROOM_BLOCK) return BROWN_MUSHROOM_BLOCK;
        if (material == Material.BROWN_SHULKER_BOX) return BROWN_SHULKER_BOX;
        if (material == Material.BROWN_STAINED_GLASS) return BROWN_STAINED_GLASS;
        if (material == Material.BROWN_TERRACOTTA) return BROWN_TERRACOTTA;
        if (material == Material.BROWN_WOOL) return BROWN_WOOL;
        if (material == Material.BUBBLE_CORAL) return BUBBLE_CORAL;
        if (material == Material.BUBBLE_CORAL_BLOCK) return BUBBLE_CORAL_BLOCK;
        if (material == Material.BUBBLE_CORAL_FAN) return BUBBLE_CORAL_FAN;
        if (material == Material.BUDDING_AMETHYST) return BUDDING_AMETHYST;
        if (material == Material.CALCITE) return CALCITE;
        if (material == Material.CANDLE) return CANDLE;
        if (material == Material.CARVED_PUMPKIN) return CARVED_PUMPKIN;
        if (material == Material.CAVE_VINES) return CAVE_VINES;
        if (material == Material.CAVE_VINES_PLANT) return CAVE_VINES_PLANT;
        if (material == Material.CHAIN) return CHAIN;
        if (material == Material.CHISELED_DEEPSLATE) return CHISELED_DEEPSLATE;
        if (material == Material.CHISELED_NETHER_BRICKS) return CHISELED_NETHER_BRICKS;
        if (material == Material.CHISELED_POLISHED_BLACKSTONE) return CHISELED_POLISHED_BLACKSTONE;
        if (material == Material.CHISELED_QUARTZ_BLOCK) return CHISELED_QUARTZ_BLOCK;
        if (material == Material.CHISELED_RED_SANDSTONE) return CHISELED_RED_SANDSTONE;
        if (material == Material.CHISELED_SANDSTONE) return CHISELED_SANDSTONE;
        if (material == Material.CHISELED_STONE_BRICKS) return CHISELED_STONE_BRICKS;
        if (material == Material.CHORUS_FLOWER) return CHORUS_FLOWER;
        if (material == Material.CHORUS_PLANT) return CHORUS_PLANT;
        if (material == Material.CLAY) return CLAY;
        if (material == Material.COAL_BLOCK) return COAL_BLOCK;
        if (material == Material.COAL_ORE) return COAL_ORE;
        if (material == Material.COARSE_DIRT) return COARSE_DIRT;
        if (material == Material.COBBLED_DEEPSLATE) return COBBLED_DEEPSLATE;
        if (material == Material.COBBLESTONE) return COBBLESTONE;
        if (material == Material.COBWEB) return COBWEB;
        if (material == Material.COMPARATOR) return COMPARATOR;
        if (material == Material.CONDUIT) return CONDUIT;
        if (material == Material.COPPER_BLOCK) return COPPER_BLOCK;
        if (material == Material.COPPER_ORE) return COPPER_ORE;
        if (material == Material.CORNFLOWER) return CORNFLOWER;
        if (material == Material.CRACKED_DEEPSLATE_BRICKS) return CRACKED_DEEPSLATE_BRICKS;
        if (material == Material.CRACKED_DEEPSLATE_TILES) return CRACKED_DEEPSLATE_TILES;
        if (material == Material.CRACKED_NETHER_BRICKS) return CRACKED_NETHER_BRICKS;
        if (material == Material.CRACKED_POLISHED_BLACKSTONE_BRICKS) return CRACKED_POLISHED_BLACKSTONE_BRICKS;
        if (material == Material.CRACKED_STONE_BRICKS) return CRACKED_STONE_BRICKS;
        if (material == Material.CRIMSON_FUNGUS) return CRIMSON_FUNGUS;
        if (material == Material.CRIMSON_NYLIUM) return CRIMSON_NYLIUM;
        if (material == Material.CRIMSON_PLANKS) return CRIMSON_PLANKS;
        if (material == Material.CRIMSON_ROOTS) return CRIMSON_ROOTS;
        if (material == Material.CRIMSON_STEM) return CRIMSON_STEM;
        if (material == Material.CRIMSON_TRAPDOOR) return CRIMSON_TRAPDOOR;
        if (material == Material.CRYING_OBSIDIAN) return CRYING_OBSIDIAN;
        if (material == Material.CUT_COPPER) return CUT_COPPER;
        if (material == Material.CUT_RED_SANDSTONE) return CUT_RED_SANDSTONE;
        if (material == Material.CUT_SANDSTONE) return CUT_SANDSTONE;
        if (material == Material.CYAN_CANDLE) return CYAN_CANDLE;
        if (material == Material.CYAN_CONCRETE) return CYAN_CONCRETE;
        if (material == Material.CYAN_CONCRETE_POWDER) return CYAN_CONCRETE_POWDER;
        if (material == Material.CYAN_GLAZED_TERRACOTTA) return CYAN_GLAZED_TERRACOTTA;
        if (material == Material.CYAN_SHULKER_BOX) return CYAN_SHULKER_BOX;
        if (material == Material.CYAN_STAINED_GLASS) return CYAN_STAINED_GLASS;
        if (material == Material.CYAN_TERRACOTTA) return CYAN_TERRACOTTA;
        if (material == Material.CYAN_WOOL) return CYAN_WOOL;
        if (material == Material.DANDELION) return DANDELION;
        if (material == Material.DARK_OAK_LEAVES) return DARK_OAK_LEAVES;
        if (material == Material.DARK_OAK_LOG) return DARK_OAK_LOG;
        if (material == Material.DARK_OAK_PLANKS) return DARK_OAK_PLANKS;
        if (material == Material.DARK_OAK_SAPLING) return DARK_OAK_SAPLING;
        if (material == Material.DARK_OAK_TRAPDOOR) return DARK_OAK_TRAPDOOR;
        if (material == Material.DARK_PRISMARINE) return DARK_PRISMARINE;
        if (material == Material.DEAD_BRAIN_CORAL) return DEAD_BRAIN_CORAL;
        if (material == Material.DEAD_BRAIN_CORAL_BLOCK) return DEAD_BRAIN_CORAL_BLOCK;
        if (material == Material.DEAD_BRAIN_CORAL_FAN) return DEAD_BRAIN_CORAL_FAN;
        if (material == Material.DEAD_BUBBLE_CORAL) return DEAD_BUBBLE_CORAL;
        if (material == Material.DEAD_BUBBLE_CORAL_BLOCK) return DEAD_BUBBLE_CORAL_BLOCK;
        if (material == Material.DEAD_BUBBLE_CORAL_FAN) return DEAD_BUBBLE_CORAL_FAN;
        if (material == Material.DEAD_BUSH) return DEAD_BUSH;
        if (material == Material.DEAD_FIRE_CORAL) return DEAD_FIRE_CORAL;
        if (material == Material.DEAD_FIRE_CORAL_BLOCK) return DEAD_FIRE_CORAL_BLOCK;
        if (material == Material.DEAD_FIRE_CORAL_FAN) return DEAD_FIRE_CORAL_FAN;
        if (material == Material.DEAD_HORN_CORAL) return DEAD_HORN_CORAL;
        if (material == Material.DEAD_HORN_CORAL_BLOCK) return DEAD_HORN_CORAL_BLOCK;
        if (material == Material.DEAD_HORN_CORAL_FAN) return DEAD_HORN_CORAL_FAN;
        if (material == Material.DEAD_TUBE_CORAL) return DEAD_TUBE_CORAL;
        if (material == Material.DEAD_TUBE_CORAL_BLOCK) return DEAD_TUBE_CORAL_BLOCK;
        if (material == Material.DEAD_TUBE_CORAL_FAN) return DEAD_TUBE_CORAL_FAN;
        if (material == Material.DEEPSLATE) return DEEPSLATE;
        if (material == Material.DEEPSLATE_BRICKS) return DEEPSLATE_BRICKS;
        if (material == Material.DEEPSLATE_COAL_ORE) return DEEPSLATE_COAL_ORE;
        if (material == Material.DEEPSLATE_COPPER_ORE) return DEEPSLATE_COPPER_ORE;
        if (material == Material.DEEPSLATE_DIAMOND_ORE) return DEEPSLATE_DIAMOND_ORE;
        if (material == Material.DEEPSLATE_EMERALD_ORE) return DEEPSLATE_EMERALD_ORE;
        if (material == Material.DEEPSLATE_GOLD_ORE) return DEEPSLATE_GOLD_ORE;
        if (material == Material.DEEPSLATE_IRON_ORE) return DEEPSLATE_IRON_ORE;
        if (material == Material.DEEPSLATE_LAPIS_ORE) return DEEPSLATE_LAPIS_ORE;
        if (material == Material.DEEPSLATE_REDSTONE_ORE) return DEEPSLATE_REDSTONE_ORE;
        if (material == Material.DEEPSLATE_TILES) return DEEPSLATE_TILES;
        if (material == Material.DETECTOR_RAIL) return DETECTOR_RAIL;
        if (material == Material.DIAMOND_BLOCK) return DIAMOND_BLOCK;
        if (material == Material.DIAMOND_ORE) return DIAMOND_ORE;
        if (material == Material.DIORITE) return DIORITE;
        if (material == Material.DIRT) return DIRT;
        if (material == Material.DRAGON_EGG) return DRAGON_EGG;
        if (material == Material.DRIPSTONE_BLOCK) return DRIPSTONE_BLOCK;
        if (material == Material.EMERALD_BLOCK) return EMERALD_BLOCK;
        if (material == Material.EMERALD_ORE) return EMERALD_ORE;
        if (material == Material.END_ROD) return END_ROD;
        if (material == Material.END_STONE) return END_STONE;
        if (material == Material.END_STONE_BRICKS) return END_STONE_BRICKS;
        if (material == Material.EXPOSED_COPPER) return EXPOSED_COPPER;
        if (material == Material.EXPOSED_CUT_COPPER) return EXPOSED_CUT_COPPER;
        if (material == Material.FARMLAND) return FARMLAND;
        if (material == Material.FERN) return FERN;
        if (material == Material.FIRE_CORAL) return FIRE_CORAL;
        if (material == Material.FIRE_CORAL_BLOCK) return FIRE_CORAL_BLOCK;
        if (material == Material.FIRE_CORAL_FAN) return FIRE_CORAL_FAN;
        if (material == Material.FLOWERING_AZALEA_LEAVES) return FLOWERING_AZALEA_LEAVES;
        if (material == Material.FLOWER_POT) return FLOWER_POT;
        if (material == Material.FROGSPAWN) return FROGSPAWN;
        if (material == Material.GILDED_BLACKSTONE) return GILDED_BLACKSTONE;
        if (material == Material.GLASS) return GLASS;
        if (material == Material.GLOWSTONE) return GLOWSTONE;
        if (material == Material.GLOW_ITEM_FRAME) return GLOW_ITEM_FRAME;
        if (material == Material.GLOW_LICHEN) return GLOW_LICHEN;
        if (material == Material.GOLD_BLOCK) return GOLD_BLOCK;
        if (material == Material.GOLD_ORE) return GOLD_ORE;
        if (material == Material.GRANITE) return GRANITE;
        if (material == Material.GRAVEL) return GRAVEL;
        if (material == Material.GRAY_CANDLE) return GRAY_CANDLE;
        if (material == Material.GRAY_CONCRETE) return GRAY_CONCRETE;
        if (material == Material.GRAY_CONCRETE_POWDER) return GRAY_CONCRETE_POWDER;
        if (material == Material.GRAY_GLAZED_TERRACOTTA) return GRAY_GLAZED_TERRACOTTA;
        if (material == Material.GRAY_SHULKER_BOX) return GRAY_SHULKER_BOX;
        if (material == Material.GRAY_STAINED_GLASS) return GRAY_STAINED_GLASS;
        if (material == Material.GRAY_TERRACOTTA) return GRAY_TERRACOTTA;
        if (material == Material.GRAY_WOOL) return GRAY_WOOL;
        if (material == Material.GREEN_CANDLE) return GREEN_CANDLE;
        if (material == Material.GREEN_CONCRETE) return GREEN_CONCRETE;
        if (material == Material.GREEN_CONCRETE_POWDER) return GREEN_CONCRETE_POWDER;
        if (material == Material.GREEN_GLAZED_TERRACOTTA) return GREEN_GLAZED_TERRACOTTA;
        if (material == Material.GREEN_SHULKER_BOX) return GREEN_SHULKER_BOX;
        if (material == Material.GREEN_STAINED_GLASS) return GREEN_STAINED_GLASS;
        if (material == Material.GREEN_TERRACOTTA) return GREEN_TERRACOTTA;
        if (material == Material.GREEN_WOOL) return GREEN_WOOL;
        if (material == Material.HANGING_ROOTS) return HANGING_ROOTS;
        if (material == Material.HONEYCOMB_BLOCK) return HONEYCOMB_BLOCK;
        if (material == Material.HORN_CORAL) return HORN_CORAL;
        if (material == Material.HORN_CORAL_BLOCK) return HORN_CORAL_BLOCK;
        if (material == Material.HORN_CORAL_FAN) return HORN_CORAL_FAN;
        if (material == Material.ICE) return ICE;
        if (material == Material.IRON_BARS) return IRON_BARS;
        if (material == Material.IRON_BLOCK) return IRON_BLOCK;
        if (material == Material.IRON_ORE) return IRON_ORE;
        if (material == Material.IRON_TRAPDOOR) return IRON_TRAPDOOR;
        if (material == Material.ITEM_FRAME) return ITEM_FRAME;
        if (material == Material.JACK_O_LANTERN) return JACK_O_LANTERN;
        if (material == Material.JUNGLE_LEAVES) return JUNGLE_LEAVES;
        if (material == Material.JUNGLE_LOG) return JUNGLE_LOG;
        if (material == Material.JUNGLE_PLANKS) return JUNGLE_PLANKS;
        if (material == Material.JUNGLE_SAPLING) return JUNGLE_SAPLING;
        if (material == Material.JUNGLE_TRAPDOOR) return JUNGLE_TRAPDOOR;
        if (material == Material.KELP) return KELP;
        if (material == Material.KELP_PLANT) return KELP_PLANT;
        if (material == Material.LADDER) return LADDER;
        if (material == Material.LANTERN) return LANTERN;
        if (material == Material.LAPIS_BLOCK) return LAPIS_BLOCK;
        if (material == Material.LAPIS_ORE) return LAPIS_ORE;
        if (material == Material.LARGE_AMETHYST_BUD) return LARGE_AMETHYST_BUD;
        if (material == Material.LEVER) return LEVER;
        if (material == Material.LIGHTNING_ROD) return LIGHTNING_ROD;
        if (material == Material.LIGHT_BLUE_CANDLE) return LIGHT_BLUE_CANDLE;
        if (material == Material.LIGHT_BLUE_CONCRETE) return LIGHT_BLUE_CONCRETE;
        if (material == Material.LIGHT_BLUE_CONCRETE_POWDER) return LIGHT_BLUE_CONCRETE_POWDER;
        if (material == Material.LIGHT_BLUE_GLAZED_TERRACOTTA) return LIGHT_BLUE_GLAZED_TERRACOTTA;
        if (material == Material.LIGHT_BLUE_SHULKER_BOX) return LIGHT_BLUE_SHULKER_BOX;
        if (material == Material.LIGHT_BLUE_STAINED_GLASS) return LIGHT_BLUE_STAINED_GLASS;
        if (material == Material.LIGHT_BLUE_TERRACOTTA) return LIGHT_BLUE_TERRACOTTA;
        if (material == Material.LIGHT_BLUE_WOOL) return LIGHT_BLUE_WOOL;
        if (material == Material.LIGHT_GRAY_CANDLE) return LIGHT_GRAY_CANDLE;
        if (material == Material.LIGHT_GRAY_CONCRETE) return LIGHT_GRAY_CONCRETE;
        if (material == Material.LIGHT_GRAY_CONCRETE_POWDER) return LIGHT_GRAY_CONCRETE_POWDER;
        if (material == Material.LIGHT_GRAY_GLAZED_TERRACOTTA) return LIGHT_GRAY_GLAZED_TERRACOTTA;
        if (material == Material.LIGHT_GRAY_SHULKER_BOX) return LIGHT_GRAY_SHULKER_BOX;
        if (material == Material.LIGHT_GRAY_STAINED_GLASS) return LIGHT_GRAY_STAINED_GLASS;
        if (material == Material.LIGHT_GRAY_TERRACOTTA) return LIGHT_GRAY_TERRACOTTA;
        if (material == Material.LIGHT_GRAY_WOOL) return LIGHT_GRAY_WOOL;
        if (material == Material.LILY_OF_THE_VALLEY) return LILY_OF_THE_VALLEY;
        if (material == Material.LILY_PAD) return LILY_PAD;
        if (material == Material.LIME_CANDLE) return LIME_CANDLE;
        if (material == Material.LIME_CONCRETE) return LIME_CONCRETE;
        if (material == Material.LIME_CONCRETE_POWDER) return LIME_CONCRETE_POWDER;
        if (material == Material.LIME_GLAZED_TERRACOTTA) return LIME_GLAZED_TERRACOTTA;
        if (material == Material.LIME_SHULKER_BOX) return LIME_SHULKER_BOX;
        if (material == Material.LIME_STAINED_GLASS) return LIME_STAINED_GLASS;
        if (material == Material.LIME_TERRACOTTA) return LIME_TERRACOTTA;
        if (material == Material.LIME_WOOL) return LIME_WOOL;
        if (material == Material.MAGENTA_CANDLE) return MAGENTA_CANDLE;
        if (material == Material.MAGENTA_CONCRETE) return MAGENTA_CONCRETE;
        if (material == Material.MAGENTA_CONCRETE_POWDER) return MAGENTA_CONCRETE_POWDER;
        if (material == Material.MAGENTA_GLAZED_TERRACOTTA) return MAGENTA_GLAZED_TERRACOTTA;
        if (material == Material.MAGENTA_SHULKER_BOX) return MAGENTA_SHULKER_BOX;
        if (material == Material.MAGENTA_STAINED_GLASS) return MAGENTA_STAINED_GLASS;
        if (material == Material.MAGENTA_TERRACOTTA) return MAGENTA_TERRACOTTA;
        if (material == Material.MAGENTA_WOOL) return MAGENTA_WOOL;
        if (material == Material.MANGROVE_LEAVES) return MANGROVE_LEAVES;
        if (material == Material.MANGROVE_LOG) return MANGROVE_LOG;
        if (material == Material.MANGROVE_PLANKS) return MANGROVE_PLANKS;
        if (material == Material.MANGROVE_PROPAGULE) return MANGROVE_PROPAGULE;
        if (material == Material.MANGROVE_TRAPDOOR) return MANGROVE_TRAPDOOR;
        if (material == Material.MEDIUM_AMETHYST_BUD) return MEDIUM_AMETHYST_BUD;
        if (material == Material.MELON_STEM) return MELON_STEM;
        if (material == Material.MOSSY_COBBLESTONE) return MOSSY_COBBLESTONE;
        if (material == Material.MOSSY_STONE_BRICKS) return MOSSY_STONE_BRICKS;
        if (material == Material.MOSS_BLOCK) return MOSS_BLOCK;
        if (material == Material.MUD) return MUD;
        if (material == Material.MUD_BRICKS) return MUD_BRICKS;
        if (material == Material.MUSHROOM_STEM) return MUSHROOM_STEM;
        if (material == Material.NETHERITE_BLOCK) return NETHERITE_BLOCK;
        if (material == Material.NETHERRACK) return NETHERRACK;
        if (material == Material.NETHER_BRICKS) return NETHER_BRICKS;
        if (material == Material.NETHER_GOLD_ORE) return NETHER_GOLD_ORE;
        if (material == Material.NETHER_PORTAL) return NETHER_PORTAL;
        if (material == Material.NETHER_QUARTZ_ORE) return NETHER_QUARTZ_ORE;
        if (material == Material.NETHER_SPROUTS) return NETHER_SPROUTS;
        if (material == Material.NETHER_WART_BLOCK) return NETHER_WART_BLOCK;
        if (material == Material.NOTE_BLOCK) return NOTE_BLOCK;
        if (material == Material.OAK_LEAVES) return OAK_LEAVES;
        if (material == Material.OAK_LOG) return OAK_LOG;
        if (material == Material.OAK_PLANKS) return OAK_PLANKS;
        if (material == Material.OAK_SAPLING) return OAK_SAPLING;
        if (material == Material.OAK_TRAPDOOR) return OAK_TRAPDOOR;
        if (material == Material.OBSIDIAN) return OBSIDIAN;
        if (material == Material.ORANGE_CANDLE) return ORANGE_CANDLE;
        if (material == Material.ORANGE_CONCRETE) return ORANGE_CONCRETE;
        if (material == Material.ORANGE_CONCRETE_POWDER) return ORANGE_CONCRETE_POWDER;
        if (material == Material.ORANGE_GLAZED_TERRACOTTA) return ORANGE_GLAZED_TERRACOTTA;
        if (material == Material.ORANGE_SHULKER_BOX) return ORANGE_SHULKER_BOX;
        if (material == Material.ORANGE_STAINED_GLASS) return ORANGE_STAINED_GLASS;
        if (material == Material.ORANGE_TERRACOTTA) return ORANGE_TERRACOTTA;
        if (material == Material.ORANGE_TULIP) return ORANGE_TULIP;
        if (material == Material.ORANGE_WOOL) return ORANGE_WOOL;
        if (material == Material.OXEYE_DAISY) return OXEYE_DAISY;
        if (material == Material.OXIDIZED_COPPER) return OXIDIZED_COPPER;
        if (material == Material.OXIDIZED_CUT_COPPER) return OXIDIZED_CUT_COPPER;
        if (material == Material.PACKED_ICE) return PACKED_ICE;
        if (material == Material.PACKED_MUD) return PACKED_MUD;
        if (material == Material.PINK_CANDLE) return PINK_CANDLE;
        if (material == Material.PINK_CONCRETE) return PINK_CONCRETE;
        if (material == Material.PINK_CONCRETE_POWDER) return PINK_CONCRETE_POWDER;
        if (material == Material.PINK_GLAZED_TERRACOTTA) return PINK_GLAZED_TERRACOTTA;
        if (material == Material.PINK_SHULKER_BOX) return PINK_SHULKER_BOX;
        if (material == Material.PINK_STAINED_GLASS) return PINK_STAINED_GLASS;
        if (material == Material.PINK_TERRACOTTA) return PINK_TERRACOTTA;
        if (material == Material.PINK_TULIP) return PINK_TULIP;
        if (material == Material.PINK_WOOL) return PINK_WOOL;
        if (material == Material.POLISHED_ANDESITE) return POLISHED_ANDESITE;
        if (material == Material.POLISHED_BLACKSTONE) return POLISHED_BLACKSTONE;
        if (material == Material.POLISHED_BLACKSTONE_BRICKS) return POLISHED_BLACKSTONE_BRICKS;
        if (material == Material.POLISHED_DEEPSLATE) return POLISHED_DEEPSLATE;
        if (material == Material.POLISHED_DIORITE) return POLISHED_DIORITE;
        if (material == Material.POLISHED_GRANITE) return POLISHED_GRANITE;
        if (material == Material.POPPY) return POPPY;
        if (material == Material.POWDER_SNOW) return POWDER_SNOW;
        if (material == Material.POWERED_RAIL) return POWERED_RAIL;
        if (material == Material.PRISMARINE) return PRISMARINE;
        if (material == Material.PRISMARINE_BRICKS) return PRISMARINE_BRICKS;
        if (material == Material.PUMPKIN_STEM) return PUMPKIN_STEM;
        if (material == Material.PURPLE_CANDLE) return PURPLE_CANDLE;
        if (material == Material.PURPLE_CONCRETE) return PURPLE_CONCRETE;
        if (material == Material.PURPLE_CONCRETE_POWDER) return PURPLE_CONCRETE_POWDER;
        if (material == Material.PURPLE_GLAZED_TERRACOTTA) return PURPLE_GLAZED_TERRACOTTA;
        if (material == Material.PURPLE_SHULKER_BOX) return PURPLE_SHULKER_BOX;
        if (material == Material.PURPLE_STAINED_GLASS) return PURPLE_STAINED_GLASS;
        if (material == Material.PURPLE_TERRACOTTA) return PURPLE_TERRACOTTA;
        if (material == Material.PURPLE_WOOL) return PURPLE_WOOL;
        if (material == Material.PURPUR_BLOCK) return PURPUR_BLOCK;
        if (material == Material.PURPUR_PILLAR) return PURPUR_PILLAR;
        if (material == Material.QUARTZ_BRICKS) return QUARTZ_BRICKS;
        if (material == Material.QUARTZ_PILLAR) return QUARTZ_PILLAR;
        if (material == Material.RAIL) return RAIL;
        if (material == Material.RAW_COPPER_BLOCK) return RAW_COPPER_BLOCK;
        if (material == Material.RAW_GOLD_BLOCK) return RAW_GOLD_BLOCK;
        if (material == Material.RAW_IRON_BLOCK) return RAW_IRON_BLOCK;
        if (material == Material.REDSTONE_BLOCK) return REDSTONE_BLOCK;
        if (material == Material.REDSTONE_LAMP) return REDSTONE_LAMP;
        if (material == Material.REDSTONE_ORE) return REDSTONE_ORE;
        if (material == Material.REDSTONE_TORCH) return REDSTONE_TORCH;
        if (material == Material.RED_CANDLE) return RED_CANDLE;
        if (material == Material.RED_CONCRETE) return RED_CONCRETE;
        if (material == Material.RED_CONCRETE_POWDER) return RED_CONCRETE_POWDER;
        if (material == Material.RED_GLAZED_TERRACOTTA) return RED_GLAZED_TERRACOTTA;
        if (material == Material.RED_MUSHROOM) return RED_MUSHROOM;
        if (material == Material.RED_MUSHROOM_BLOCK) return RED_MUSHROOM_BLOCK;
        if (material == Material.RED_NETHER_BRICKS) return RED_NETHER_BRICKS;
        if (material == Material.RED_SAND) return RED_SAND;
        if (material == Material.RED_SANDSTONE) return RED_SANDSTONE;
        if (material == Material.RED_SHULKER_BOX) return RED_SHULKER_BOX;
        if (material == Material.RED_STAINED_GLASS) return RED_STAINED_GLASS;
        if (material == Material.RED_TERRACOTTA) return RED_TERRACOTTA;
        if (material == Material.RED_TULIP) return RED_TULIP;
        if (material == Material.RED_WOOL) return RED_WOOL;
        if (material == Material.REPEATER) return REPEATER;
        if (material == Material.ROOTED_DIRT) return ROOTED_DIRT;
        if (material == Material.SAND) return SAND;
        if (material == Material.SANDSTONE) return SANDSTONE;
        if (material == Material.SCULK) return SCULK;
        if (material == Material.SCULK_VEIN) return SCULK_VEIN;
        if (material == Material.SEAGRASS) return SEAGRASS;
        if (material == Material.SEA_LANTERN) return SEA_LANTERN;
        if (material == Material.SEA_PICKLE) return SEA_PICKLE;
        if (material == Material.SHROOMLIGHT) return SHROOMLIGHT;
        if (material == Material.SHULKER_BOX) return SHULKER_BOX;
        if (material == Material.SLIME_BLOCK) return SLIME_BLOCK;
        if (material == Material.SMALL_AMETHYST_BUD) return SMALL_AMETHYST_BUD;
        if (material == Material.SMOOTH_BASALT) return SMOOTH_BASALT;
        if (material == Material.SMOOTH_STONE) return SMOOTH_STONE;
        if (material == Material.SNOW) return SNOW;
        if (material == Material.SOUL_LANTERN) return SOUL_LANTERN;
        if (material == Material.SOUL_SAND) return SOUL_SAND;
        if (material == Material.SOUL_SOIL) return SOUL_SOIL;
        if (material == Material.SOUL_TORCH) return SOUL_TORCH;
        if (material == Material.SPAWNER) return SPAWNER;
        if (material == Material.SPONGE) return SPONGE;
        if (material == Material.SPORE_BLOSSOM) return SPORE_BLOSSOM;
        if (material == Material.SPRUCE_LEAVES) return SPRUCE_LEAVES;
        if (material == Material.SPRUCE_LOG) return SPRUCE_LOG;
        if (material == Material.SPRUCE_PLANKS) return SPRUCE_PLANKS;
        if (material == Material.SPRUCE_SAPLING) return SPRUCE_SAPLING;
        if (material == Material.SPRUCE_TRAPDOOR) return SPRUCE_TRAPDOOR;
        if (material == Material.STONE) return STONE;
        if (material == Material.STONE_BRICKS) return STONE_BRICKS;
        if (material == Material.STRIPPED_ACACIA_LOG) return STRIPPED_ACACIA_LOG;
        if (material == Material.STRIPPED_BAMBOO_BLOCK) return STRIPPED_BAMBOO_BLOCK;
        if (material == Material.STRIPPED_BIRCH_LOG) return STRIPPED_BIRCH_LOG;
        if (material == Material.STRIPPED_CRIMSON_STEM) return STRIPPED_CRIMSON_STEM;
        if (material == Material.STRIPPED_DARK_OAK_LOG) return STRIPPED_DARK_OAK_LOG;
        if (material == Material.STRIPPED_JUNGLE_LOG) return STRIPPED_JUNGLE_LOG;
        if (material == Material.STRIPPED_MANGROVE_LOG) return STRIPPED_MANGROVE_LOG;
        if (material == Material.STRIPPED_OAK_LOG) return STRIPPED_OAK_LOG;
        if (material == Material.STRIPPED_SPRUCE_LOG) return STRIPPED_SPRUCE_LOG;
        if (material == Material.STRIPPED_WARPED_STEM) return STRIPPED_WARPED_STEM;
        if (material == Material.STRUCTURE_BLOCK) return STRUCTURE_BLOCK;
        if (material == Material.SUGAR_CANE) return SUGAR_CANE;
        if (material == Material.TERRACOTTA) return TERRACOTTA;
        if (material == Material.TINTED_GLASS) return TINTED_GLASS;
        if (material == Material.TORCH) return TORCH;
        if (material == Material.TRIPWIRE) return TRIPWIRE;
        if (material == Material.TRIPWIRE_HOOK) return TRIPWIRE_HOOK;
        if (material == Material.TUBE_CORAL) return TUBE_CORAL;
        if (material == Material.TUBE_CORAL_BLOCK) return TUBE_CORAL_BLOCK;
        if (material == Material.TUBE_CORAL_FAN) return TUBE_CORAL_FAN;
        if (material == Material.TUFF) return TUFF;
        if (material == Material.TURTLE_EGG) return TURTLE_EGG;
        if (material == Material.TWISTING_VINES) return TWISTING_VINES;
        if (material == Material.TWISTING_VINES_PLANT) return TWISTING_VINES_PLANT;
        if (material == Material.VINE) return VINE;
        if (material == Material.WARPED_FUNGUS) return WARPED_FUNGUS;
        if (material == Material.WARPED_NYLIUM) return WARPED_NYLIUM;
        if (material == Material.WARPED_PLANKS) return WARPED_PLANKS;
        if (material == Material.WARPED_ROOTS) return WARPED_ROOTS;
        if (material == Material.WARPED_STEM) return WARPED_STEM;
        if (material == Material.WARPED_TRAPDOOR) return WARPED_TRAPDOOR;
        if (material == Material.WARPED_WART_BLOCK) return WARPED_WART_BLOCK;
        if (material == Material.WEATHERED_COPPER) return WEATHERED_COPPER;
        if (material == Material.WEATHERED_CUT_COPPER) return WEATHERED_CUT_COPPER;
        if (material == Material.WEEPING_VINES) return WEEPING_VINES;
        if (material == Material.WEEPING_VINES_PLANT) return WEEPING_VINES_PLANT;
        if (material == Material.WET_SPONGE) return WET_SPONGE;
        if (material == Material.WHITE_CANDLE) return WHITE_CANDLE;
        if (material == Material.WHITE_CONCRETE) return WHITE_CONCRETE;
        if (material == Material.WHITE_CONCRETE_POWDER) return WHITE_CONCRETE_POWDER;
        if (material == Material.WHITE_GLAZED_TERRACOTTA) return WHITE_GLAZED_TERRACOTTA;
        if (material == Material.WHITE_SHULKER_BOX) return WHITE_SHULKER_BOX;
        if (material == Material.WHITE_STAINED_GLASS) return WHITE_STAINED_GLASS;
        if (material == Material.WHITE_TERRACOTTA) return WHITE_TERRACOTTA;
        if (material == Material.WHITE_TULIP) return WHITE_TULIP;
        if (material == Material.WHITE_WOOL) return WHITE_WOOL;
        if (material == Material.WITHER_ROSE) return WITHER_ROSE;
        if (material == Material.YELLOW_CANDLE) return YELLOW_CANDLE;
        if (material == Material.YELLOW_CONCRETE) return YELLOW_CONCRETE;
        if (material == Material.YELLOW_CONCRETE_POWDER) return YELLOW_CONCRETE_POWDER;
        if (material == Material.YELLOW_GLAZED_TERRACOTTA) return YELLOW_GLAZED_TERRACOTTA;
        if (material == Material.YELLOW_SHULKER_BOX) return YELLOW_SHULKER_BOX;
        if (material == Material.YELLOW_STAINED_GLASS) return YELLOW_STAINED_GLASS;
        if (material == Material.YELLOW_TERRACOTTA) return YELLOW_TERRACOTTA;
        if (material == Material.YELLOW_WOOL) return YELLOW_WOOL;
        if (material == Material.CHERRY_LEAVES) return CHERRY_LEAVES;
        if (material == Material.CHERRY_LOG) return CHERRY_LOG;
        if (material == Material.CHERRY_PLANKS) return CHERRY_PLANKS;
        if (material == Material.CHERRY_SAPLING) return CHERRY_SAPLING;
        if (material == Material.CHERRY_TRAPDOOR) return CHERRY_TRAPDOOR;
        if (material == Material.CHISELED_COPPER) return CHISELED_COPPER;
        if (material == Material.CHISELED_TUFF) return CHISELED_TUFF;
        if (material == Material.CHISELED_TUFF_BRICKS) return CHISELED_TUFF_BRICKS;
        if (material == Material.COPPER_BULB) return COPPER_BULB;
        if (material == Material.COPPER_GRATE) return COPPER_GRATE;
        if (material == Material.COPPER_TRAPDOOR) return COPPER_TRAPDOOR;
        if (material == Material.EXPOSED_CHISELED_COPPER) return EXPOSED_CHISELED_COPPER;
        if (material == Material.EXPOSED_COPPER_BULB) return EXPOSED_COPPER_BULB;
        if (material == Material.EXPOSED_COPPER_GRATE) return EXPOSED_COPPER_GRATE;
        if (material == Material.EXPOSED_COPPER_TRAPDOOR) return EXPOSED_COPPER_TRAPDOOR;
        if (material == Material.HEAVY_CORE) return HEAVY_CORE;
        if (material == Material.OXIDIZED_CHISELED_COPPER) return OXIDIZED_CHISELED_COPPER;
        if (material == Material.OXIDIZED_COPPER_BULB) return OXIDIZED_COPPER_BULB;
        if (material == Material.OXIDIZED_COPPER_GRATE) return OXIDIZED_COPPER_GRATE;
        if (material == Material.OXIDIZED_COPPER_TRAPDOOR) return OXIDIZED_COPPER_TRAPDOOR;
        if (material == Material.PINK_PETALS) return PINK_PETALS;
        if (material == Material.POLISHED_TUFF) return POLISHED_TUFF;
        if (material == Material.SHORT_GRASS) return SHORT_GRASS;
        if (material == Material.STRIPPED_CHERRY_LOG) return STRIPPED_CHERRY_LOG;
        if (material == Material.TORCHFLOWER) return TORCHFLOWER;
        if (material == Material.TUFF_BRICKS) return TUFF_BRICKS;
        if (material == Material.WEATHERED_CHISELED_COPPER) return WEATHERED_CHISELED_COPPER;
        if (material == Material.WEATHERED_COPPER_BULB) return WEATHERED_COPPER_BULB;
        if (material == Material.WEATHERED_COPPER_GRATE) return WEATHERED_COPPER_GRATE;
        if (material == Material.WEATHERED_COPPER_TRAPDOOR) return WEATHERED_COPPER_TRAPDOOR;
        return null;
    }

    public static Character fromMaterialElse(Material material, Character elseCharacter) {
        Character current = fromMaterial(material);
        return current != null ? current : elseCharacter;
    }
}